### Importando as bibliotecas

In [50]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import time
from io import StringIO
import openpyxl

In [51]:
# URL base da agenda tribunária
url_base = "https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria"

# Ano selecionado pelo usuário
ano_selecionado = 2025

# URL com o ano selecionado
url_com_ano = f"{url_base}/{ano_selecionado}"
url_com_ano

'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025'

In [52]:
# Realizando uma requisição GET na URL base da agenda tributária
response = requests.get(url_com_ano)
response.status_code

200

In [53]:
# analisando o conteudo 
response.content

b'<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br" xml:lang="pt-br">\n\n<head>\n    <meta charset="utf-8" />\n  <!-- Google Tag Manager -->\n  <script type="text">(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\n  new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\n  j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n  \'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n  })(window,document,\'script\',\'dataLayer\',\'GTM-NHZSKTD\');</script>\n  <!-- End Google Tag Manager -->\n\n        <script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "Organization",\n            "url": "https://www.gov.br/receitafederal",\n            "logo": "https://www.gov.br/receitafederal/logo.png"\n        }</script>\n        <script type="application/ld+json">\n        {\n            "@context": "https://schema.org",\n            "@type": "WebSite",\n            "url": "https://www.gov.br/receitafederal",\n            "potentialAction": {\n              "@type": "SearchAction",\n              "target": "https://www.gov.br/receitafederal/search?SearchableText={search_term_string}",\n              "query-input": "required name=search_term_string"\n            }\n        }</script>\n\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n\n    \n        <base href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/" /><!--[if lt IE 7]></base><![endif]-->\n    \n\n    \n        <meta property="og:title" content="2025" />\n<meta property="og:description" content="" />\n<meta property="og:type" content="article" />\n<meta property="og:url" content="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025" />\n<meta property="og:image" content="https://www.gov.br/receitafederal/logo.png" />\n\n<meta property="og:locale" content="pt_BR" />\n<meta property="og:site_name" content="Receita Federal " />\n\n\n  \n\n  \n  \n  <script type="text">\n    (function() {\n        var po = document.createElement(\'script\');\n        po.async = true;\n        po.src = document.location.protocol + \'//connect.facebook.net/pt_BR/all.js#xfbml=1\';\n        var head = document.getElementsByTagName(\'head\')[0];\n        head.appendChild(po);\n    }());\n    </script>\n\n\n\n  \n\n  <meta name="twitter:card" content="summary_large_image" />\n  <meta name="twitter:site" content="@" />\n  \n\n\n\n\n\n<meta property="creator.productor" content="https://www.gov.br/fazenda" />\n\n\n\n  \n    <link rel="stylesheet" type="text/css" href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/reset-cachekey-42de820bc50f17406b0f01f7602d9b79.css" media="screen" />\n    <link rel="stylesheet" type="text/css" href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/base-cachekey-1991302562972620f08e052a97c8b5e1.css" />\n    <style type="text/css" media="screen">@import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourceplone.app.jquerytools.dateinput-cachekey-5a249b5311d2f378428c7e7be2f636ff.css);</style>\n    <link rel="stylesheet" type="text/css" href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourceplone.formwidget.datetimestyles-cachekey-e28848a3f2f551ef01b9a0b81d2fcf30.css" />\n    <style type="text/css" media="screen">@import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/jquery.autocomplete-cachekey-a440e9cfa98b4dec71dc267a87964c31.css);</style>\n    <link rel="stylesheet" type="text/css" href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/embedder-cachekey-f5e1139b55bdafccb135ab4042abec8c.css" media="screen" />\n    <style type="text/css" media="screen">@import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcecollective.pollscsscollective.polls-cachekey-d5f72fea2e3f68069023c1f19c483d22.css);</style>\n        <!--[if lt IE 8]>    \n    \n    <link rel="stylesheet" type="text/css" href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/IEFixes-cachekey-0793ce9d8be480e2ed0228e3227efde7.css" media="screen" />\n        <![endif]-->\n    \n    <style type="text/css" media="all">@import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcepas.plugins.loginunicologinunico-cachekey-b0b1178bffe5161af33204d32599ecbf.css);</style>\n    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css" media="screen" />\n    <link rel="stylesheet" type="text/css" href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcelgpd.plugindsgov.min-cachekey-618c7f80ce75c9a81f6a4b657dcb1075.css" media="screen" />\n    <link rel="stylesheet" type="text/css" href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcegovbr.policycanais-cachekey-2f2ee33639add88e0a00d1df7cf7488c.css" />\n\n  \n  \n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policybrowser-update-cachekey-63c70a22490b29beaad3085901a45ea3.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourceplone.app.jquery-cachekey-3c746bb4a983838f10cdc0926e9ed66a.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policyfolder_contents-cachekey-884e305b01ef76397df4508c707ededd.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policycookiebar_1_3_55-cachekey-e5d51de04e2fcf108fd0e1bf692c8160.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policyapplication_cookiebar_1_3_55-cachekey-8a32efed0b2a01ba33c19f2fd57ebf22.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/collective.js.jqueryui.custom.min-cachekey-c838bf037d3098390e48cde4b3eecd77.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourceplone.formwidget.recurrencejquery.tmpl-beta1-cachekey-70b23b5b387b6e7a9a03062836d1e235.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcecollective.js.bootstrapjsbootstrap.min-cachekey-11a00508837ff5d5907db69871e85ef3.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcecollective.coverjsmain-cachekey-88bef20151707ed848d6bb4cffdb8872.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcebrasil.gov.tilesvendorjquery.jplayer.min-cachekey-25cea8128c136f33a70e2ed1dacc5eb5.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcedropdown-menu-cachekey-3d8e116f2145631124393316d3d52e37.js"></script>\n    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.min.js"></script>\n    <script type="text/javascript"></script>\n    <script type="text/javascript"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcelgpd.pluginchangeCookieImage-cachekey-52453a911ff2b5c2e7b019805f3ec46f.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcelgpd.pluginblock_cookies-cachekey-171f4aba329dae4ab47afc814ab9e0f2.js"></script>\n    <script type="text/javascript" src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/++resource++govbr.recomendacao/govbr.recom.12bf697a4cb12043ba4c.js"></script>\n\n\n\n  <link rel="stylesheet" href="https://www.gov.br/receitafederal/++resource++brasil.gov.agenda/brasilgovagenda-720c34e.css" />\n\n\n  <script defer="defer" src="https://www.gov.br/receitafederal/++resource++brasil.gov.agenda/brasilgovagenda-720c34e.js"></script>\n\n\n\n  <link rel="stylesheet" href="https://www.gov.br/receitafederal/++resource++brasil.gov.portal/brasilgovportal-ee510e4.css" />\n\n\n  <script defer="defer" src="https://www.gov.br/receitafederal/++resource++brasil.gov.portal/brasilgovportal-ee510e4.js"></script>\n\n\n\n<title>2025 \xe2\x80\x94 Receita Federal </title>\n<link rel="http://purl.org/dc/terms/subject http://schema.org/about http://xmlns.com/foaf/0.1/primaryTopic" href="http://vocab.e.gov.br/2011/03/vcge#esquema" />\n        \n    <link rel="author" href="https://www.gov.br/receitafederal/pt-br" title="Informa\xc3\xa7\xc3\xb5es do Autor" />\n\n    <link rel="canonical" href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025" />\n\n    \n    \n\n\n<script type="text/javascript">\n        jQuery(function($){\n            if (typeof($.datepicker) != "undefined"){\n              $.datepicker.setDefaults(\n                jQuery.extend($.datepicker.regional[\'pt-BR\'],\n                {dateFormat: \'dd/mm/yy\'}));\n            }\n        });\n        </script>\n\n\n\n    <link rel="alternate" href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/RSS" title="2025 - RSS 1.0" type="application/rss+xml" />\n\n    <link rel="alternate" href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/rss.xml" title="2025 - RSS 2.0" type="application/rss+xml" />\n\n    <link rel="alternate" href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/atom.xml" title="2025 - Atom" type="application/rss+xml" />\n\n\n    <link rel="search" href="https://www.gov.br/receitafederal/pt-br/@@search" title="Buscar neste site" />\n\n\n\n        \n        \n        \n        \n        \n\n        \n        <meta name="generator" content="Plone - http://plone.org" />\n    \n\n    \n    <meta content="width=device-width, initial-scale=1.0" name="viewport" />\n    <link rel="apple-touch-icon" sizes="180x180" href="/receitafederal/++theme++padrao_govbr/favicons/apple-touch-icon.png" />\n    <link rel="icon" type="image/png" sizes="32x32" href="/receitafederal/++theme++padrao_govbr/favicons/favicon-32x32.png" />\n    <link rel="shortcut icon" type="image/png" href="/receitafederal/++theme++padrao_govbr/favicons/favicon-48x48.png" />\n    <link rel="mask-icon" href="/receitafederal/++theme++padrao_govbr/favicons/safari-pinned-tab.svg" color="#00a300" />\n    <meta name="msapplication-config" content="favicons/browserconfig.xml" />\n    <meta name="theme-color" content="#00a300" />\n    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />\n    <style>\n        body.userrole-authenticated .btn.btn-success.fileinput-button span:after {\n            content: "Adicionar Arquivos" !important;\n        }\n    </style>\n    \n    <script type="module" id="barra-govbr-pro" src="https://barra.sistema.gov.br/v1/barra-govbr-wc.iife.js"></script>\n    <script type="module" src="/govbrportal/js/session.js" defer="defer"></script>\n<link href="/receitafederal/++theme++padrao_govbr/govbrtheme-8fb61a6.css" rel="stylesheet" /></head>\n\n<body id="" class="default-header-template portal-institucional template-template_cards portaltype-folder site-pt-br section-assuntos subsection-agenda-tributaria subsection-agenda-tributaria-2025 userrole-anonymous" data-base-url="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025" data-portal-url="https://www.gov.br/receitafederal" dir="ltr">\n  <!-- Google Tag Manager (noscript) -->\n  <noscript><iframe height="0" width="0" style="display:none;visibility:hidden" data-src="https://www.googletagmanager.com/ns.html?id=GTM-NHZSKTD"></iframe></noscript>\n  <!-- End Google Tag Manager (noscript) -->\n\n  <nav class="govbr-skip-menu" aria-label="Acesso r\xc3\xa1pido">\n    <a href="#wrapper" accesskey="1">\n      <span class="sr-only">Ir para o</span>\n      Conte\xc3\xbado\n      <span class="access-key">1</span>\n    </a>\n    <a href="/" accesskey="2">\n      <span class="sr-only">Ir para a</span>\n      P\xc3\xa1gina Inicial\n      <span class="access-key">2</span>\n    </a>\n    <a href="#main-navigation" accesskey="3">\n      <span class="sr-only">Ir para o menu de</span>\n      Navega\xc3\xa7\xc3\xa3o\n      <span class="access-key">3</span>\n    </a>\n    <a href="#govbr-busca-input" accesskey="4">\n      <span class="sr-only">Ir para a</span>\n      Busca\n      <span class="access-key">4</span>\n    </a>\n    <a href="#portal-footer" accesskey="5">\n      <span class="sr-only">Ir para o</span>\n      Mapa do site\n      <span class="access-key">5</span>\n    </a>\n  </nav>\n\n  <noscript aria-label="Aviso de Javascript desabilitado">\n    <dl class="portalMessage attention erro-javascript">\n      <dt>Aten\xc3\xa7\xc3\xa3o!</dt>\n      <dd>Seu navegador n\xc3\xa3o pode executar javascript. Alguns recursos podem n\xc3\xa3o funcionar corretamente.</dd>\n    </dl>\n  </noscript>\n<!-- modal session message --><!-- User --><!-- Header --><!--\n    Para habilitar o novo menu &#233; necess&#225;rio descoment&#225;-lo em:\n    govbr/institucional/viewlets/institucional_menu_govbr.pt\n    --><!-- <header id="site-header" class="has-navigation-swipe"> --><header id="site-header" class="has-navigation-dropdown" style="z-index: 999;">\n        <div class="header-wrapper secondary">\n            <barra-govbr class="width100 shadow-none show-contrast-toggle" style="width: 100%;" id="barra-govbr" titulo="Minist\xc3\xa9rio da Fazenda" signinhref="/govbrportal/inicializacao-autenticacao-openid.html" signouthref="/govbrportal/logout.html" linktitulo="https://www.gov.br/fazenda" linklogo="https://www.gov.br/pt-br" idiomas="" idiomaativo="" linksdosistema="[{&quot;title&quot;:&quot;\xc3\x93rg\xc3\xa3os do Governo&quot;,&quot;href&quot;:&quot;https://www.gov.br/pt-br/orgaos-do-governo&quot;},{&quot;title&quot;:&quot;Acesso \xc3\xa0 Informa\xc3\xa7\xc3\xa3o&quot;,&quot;href&quot;:&quot;https://www.gov.br/acessoainformacao/pt-br&quot;},{&quot;title&quot;:&quot;Legisla\xc3\xa7\xc3\xa3o&quot;,&quot;href&quot;:&quot;http://www4.planalto.gov.br/legislacao&quot;},{&quot;title&quot;:&quot;Acessibilidade&quot;,&quot;href&quot;:&quot;https://www.gov.br/governodigital/pt-br/acessibilidade-digital&quot;}]" contrastactive="false">\n            </barra-govbr>\n        </div>\n\n        <div class="main">\n            <div class="header-wrapper">\n\n                <div class="site-name-wrapper">\n                    <a class="ico-navegacao toggle-main-navigation" href="#">\n                        <span class="sr-only">Abrir menu principal de navega\xc3\xa7\xc3\xa3o</span>\n                        <span class="fa fa-bars" aria-hidden="true"></span>\n                        <span class="fa fa-times" aria-hidden="true"></span>\n                    </a>\n\n                    <!-- <a href="/" class="site-name">Nome do site</a> -->\n                    <!-- Usar nome completo -->\n                    \n                    <div class="site-name">\n                        <a href="https://www.gov.br/receitafederal/pt-br">Receita Federal </a>\n                    </div>\n                </div>\n\n                \n            <div class="termos-mais-buscados desktop">\n                <section class="source-termos-mais-buscados">\n                    <div class="source-header-termos-mais-buscados">\n                        Termos mais buscados\n                    </div>\n                    <ul class="list-termos-mais-buscados">\n                        \n                            <li class="item-termos-mais-buscados">\n                                <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=imposto de renda">\n                                   <span class="fa-solid fa-arrow-trend-up"></span>\n                                   imposto de renda\n                                </a>\n                            </li>\n                        \n                            <li class="item-termos-mais-buscados">\n                                <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=inss">\n                                   <span class="fa-solid fa-arrow-trend-up"></span>\n                                   inss\n                                </a>\n                            </li>\n                        \n                            <li class="item-termos-mais-buscados">\n                                <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=assinatura">\n                                   <span class="fa-solid fa-arrow-trend-up"></span>\n                                   assinatura\n                                </a>\n                            </li>\n                        \n                            <li class="item-termos-mais-buscados">\n                                <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=cnh social">\n                                   <span class="fa-solid fa-arrow-trend-up"></span>\n                                   cnh social\n                                </a>\n                            </li>\n                        \n                            <li class="item-termos-mais-buscados">\n                                <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=enem">\n                                   <span class="fa-solid fa-arrow-trend-up"></span>\n                                   enem\n                                </a>\n                            </li>\n                        \n                    </ul>\n                </section>\n            </div>\n            <div class="termos-mais-buscados mobile">\n                <section class="source-termos-mais-buscados">\n                    <div class="source-header-termos-mais-buscados">\n                        Termos mais buscados\n                    </div>                                \n                    <ul class="list-termos-mais-buscados">\n                        \n                            <li class="item-termos-mais-buscados">\n                                <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=imposto de renda">\n                                    <span class="fa-solid fa-arrow-trend-up"></span>\n                                    imposto de renda\n                                </a>\n                            </li>\n                        \n                            <li class="item-termos-mais-buscados">\n                                <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=inss">\n                                    <span class="fa-solid fa-arrow-trend-up"></span>\n                                    inss\n                                </a>\n                            </li>\n                        \n                            <li class="item-termos-mais-buscados">\n                                <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=assinatura">\n                                    <span class="fa-solid fa-arrow-trend-up"></span>\n                                    assinatura\n                                </a>\n                            </li>\n                        \n                    </ul>\n                

In [54]:
# analisando o conteudo deixando a mensagem do terminal mais legível
soup = BeautifulSoup(response.content, 'html.parser')
print(soup.prettify())
type(soup)

<!DOCTYPE html>
<html lang="pt-br" xml:lang="pt-br" xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta charset="utf-8"/>
  <!-- Google Tag Manager -->
  <script type="text">
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-NHZSKTD');
  </script>
  <!-- End Google Tag Manager -->
  <script type="application/ld+json">
   {
            "@context": "https://schema.org",
            "@type": "Organization",
            "url": "https://www.gov.br/receitafederal",
            "logo": "https://www.gov.br/receitafederal/logo.png"
        }
  </script>
  <script type="application/ld+json">
   {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "url": "https://www.gov.br/receitafederal",
            "potentialAction": {
              "@type": "SearchAction",
              "target": "https://www.gov.br/receitafederal/search?SearchableText={search_term_string}",
              "query-input": "required name=search_term_string"
            }
        }
  </script>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <base href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/"/>
  <!--[if lt IE 7]></base><![endif]-->
  <meta content="2025" property="og:title"/>
  <meta content="" property="og:description"/>
  <meta content="article" property="og:type"/>
  <meta content="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025" property="og:url"/>
  <meta content="https://www.gov.br/receitafederal/logo.png" property="og:image"/>
  <meta content="pt_BR" property="og:locale"/>
  <meta content="Receita Federal " property="og:site_name"/>
  <script type="text">
   (function() {
        var po = document.createElement('script');
        po.async = true;
        po.src = document.location.protocol + '//connect.facebook.net/pt_BR/all.js#xfbml=1';
        var head = document.getElementsByTagName('head')[0];
        head.appendChild(po);
    }());
  </script>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="@" name="twitter:site"/>
  <meta content="https://www.gov.br/fazenda" property="creator.productor"/>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/reset-cachekey-42de820bc50f17406b0f01f7602d9b79.css" media="screen" rel="stylesheet" type="text/css"/>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/base-cachekey-1991302562972620f08e052a97c8b5e1.css" rel="stylesheet" type="text/css"/>
  <style media="screen" type="text/css">
   @import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourceplone.app.jquerytools.dateinput-cachekey-5a249b5311d2f378428c7e7be2f636ff.css);
  </style>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourceplone.formwidget.datetimestyles-cachekey-e28848a3f2f551ef01b9a0b81d2fcf30.css" rel="stylesheet" type="text/css"/>
  <style media="screen" type="text/css">
   @import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/jquery.autocomplete-cachekey-a440e9cfa98b4dec71dc267a87964c31.css);
  </style>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/embedder-cachekey-f5e1139b55bdafccb135ab4042abec8c.css" media="screen" rel="stylesheet" type="text/css"/>
  <style media="screen" type="text/css">
   @import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcecollective.pollscsscollective.polls-cachekey-d5f72fea2e3f68069023c1f19c483d22.css);
  </style>
  <!--[if lt IE 8]>

    <link rel="stylesheet" type="text/css" href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/IEFixes-cachekey-0793ce9d8be480e2ed0228e3227efde7.css" media="screen" />
        <![endif]-->
  <style media="all" type="text/css">
   @import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcepas.plugins.loginunicologinunico-cachekey-b0b1178bffe5161af33204d32599ecbf.css);
  </style>
  <link href="//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css" media="screen" rel="stylesheet" type="text/css"/>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcelgpd.plugindsgov.min-cachekey-618c7f80ce75c9a81f6a4b657dcb1075.css" media="screen" rel="stylesheet" type="text/css"/>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcegovbr.policycanais-cachekey-2f2ee33639add88e0a00d1df7cf7488c.css" rel="stylesheet" type="text/css"/>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policybrowser-update-cachekey-63c70a22490b29beaad3085901a45ea3.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourceplone.app.jquery-cachekey-3c746bb4a983838f10cdc0926e9ed66a.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policyfolder_contents-cachekey-884e305b01ef76397df4508c707ededd.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policycookiebar_1_3_55-cachekey-e5d51de04e2fcf108fd0e1bf692c8160.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policyapplication_cookiebar_1_3_55-cachekey-8a32efed0b2a01ba33c19f2fd57ebf22.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/collective.js.jqueryui.custom.min-cachekey-c838bf037d3098390e48cde4b3eecd77.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourceplone.formwidget.recurrencejquery.tmpl-beta1-cachekey-70b23b5b387b6e7a9a03062836d1e235.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcecollective.js.bootstrapjsbootstrap.min-cachekey-11a00508837ff5d5907db69871e85ef3.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcecollective.coverjsmain-cachekey-88bef20151707ed848d6bb4cffdb8872.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcebrasil.gov.tilesvendorjquery.jplayer.min-cachekey-25cea8128c136f33a70e2ed1dacc5eb5.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcedropdown-menu-cachekey-3d8e116f2145631124393316d3d52e37.js" type="text/javascript">
  </script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.min.js" type="text/javascript">
  </script>
  <script type="text/javascript">
  </script>
  <script type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcelgpd.pluginchangeCookieImage-cachekey-52453a911ff2b5c2e7b019805f3ec46f.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcelgpd.pluginblock_cookies-cachekey-171f4aba329dae4ab47afc814ab9e0f2.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/++resource++govbr.recomendacao/govbr.recom.12bf697a4cb12043ba4c.js" type="text/javascript">
  </script>
  <link href="https://www.gov.br/receitafederal/++resource++brasil.gov.agenda/brasilgovagenda-720c34e.css" rel="stylesheet"/>
  <script defer="defer" src="https://www.gov.br/receitafederal/++resource++brasil.gov.agenda/brasilgovagenda-720c34e.js">
  </script>
  <link href="https://www.gov.br/receitafederal/++resource++brasil.gov.portal/brasilgovportal-ee510e4.css" rel="stylesheet"/>
  <script defer="defer" src="https://www.gov.br/receitafederal/++resource++brasil.gov.portal/brasilgovportal-ee510e4.js">
  </script>
  <title>
   2025 — Receita Federal
  </title>
  <link href="http://vocab.e.gov.br/2011/03/vcge#esquema" rel="http://purl.org/dc/terms/subject http://schema.org/about http://xmlns.com/foaf/0.1/primaryTopic"/>
  <link href="https://www.gov.br/receitafederal/pt-br" rel="author" title="Informações do Autor"/>
  <link href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025" rel="canonical"/>
  <script type="text/javascript">
   jQuery(function($){
            if (typeof($.datepicker) != "undefined"){
              $.datepicker.setDefaults(
                jQuery.extend($.datepicker.regional['pt-BR'],
                {dateFormat: 'dd/mm/yy'}));
            }
        });
  </script>
  <link href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/RSS" rel="alternate" title="2025 - RSS 1.0" type="application/rss+xml"/>
  <link href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/rss.xml" rel="alternate" title="2025 - RSS 2.0" type="application/rss+xml"/>
  <link href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/atom.xml" rel="alternate" title="2025 - Atom" type="application/rss+xml"/>
  <link href="https://www.gov.br/receitafederal/pt-br/@@search" rel="search" title="Buscar neste site"/>
  <meta content="Plone - http://plone.org" name="generator"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="/receitafederal/++theme++padrao_govbr/favicons/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
  <link href="/receitafederal/++theme++padrao_govbr/favicons/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
  <link href="/receitafederal/++theme++padrao_govbr/favicons/favicon-48x48.png" rel="shortcut icon" type="image/png"/>
  <link color="#00a300" href="/receitafederal/++theme++padrao_govbr/favicons/safari-pinned-tab.svg" rel="mask-icon"/>
  <meta content="favicons/browserconfig.xml" name="msapplication-config"/>
  <meta content="#00a300" name="theme-color"/>
  <link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" referrerpolicy="no-referrer" rel="stylesheet"/>
  <style>
   body.userrole-authenticated .btn.btn-success.fileinput-button span:after {
            content: "Adicionar Arquivos" !important;
        }
  </style>
  <script id="barra-govbr-pro" src="https://barra.sistema.gov.br/v1/barra-govbr-wc.iife.js" type="module">
  </script>
  <script defer="defer" src="/govbrportal/js/session.js" type="module">
  </script>
  <link href="/receitafederal/++theme++padrao_govbr/govbrtheme-8fb61a6.css" rel="stylesheet"/>
 </head>
 <body class="default-header-template portal-institucional template-template_cards portaltype-folder site-pt-br section-assuntos subsection-agenda-tributaria subsection-agenda-tributaria-2025 userrole-anonymous" data-base-url="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025" data-portal-url="https://www.gov.br/receitafederal" dir="ltr" id="">
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe data-src="https://www.googletagmanager.com/ns.html?id=GTM-NHZSKTD" height="0" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <nav aria-label="Acesso rápido" class="govbr-skip-menu">
   <a accesskey="1" href="#wrapper">
    <span class="sr-only">
     Ir para o
    </span>
    Conteúdo
    <span class="access-key">
     1
    </span>
   </a>
   <a accesskey="2" href="/">
    <span class="sr-only">
     Ir para a
    </span>
    Página Inicial
    <span class="access-key">
     2
    </span>
   </a>
   <a accesskey="3" href="#main-navigation">
    <span class="sr-only">
     Ir para o menu de
    </span>
    Navegação
    <span class="access-key">
     3
    </span>
   </a>
   <a accesskey="4" href="#govbr-busca-input">
    <span class="sr-only">
     Ir para a
    </span>
    Busca
    <span class="access-key">
     4
    </span>
   </a>
   <a accesskey="5" href="#portal-footer">
    <span class="sr-only">
     Ir para o
    </span>
    Mapa do site
    <span class="access-key">
     5
    </span>
   </a>
  </nav>
  <noscript aria-label="Aviso de Javascript desabilitado">
   <dl class="portalMessage attention erro-javascript">
    <dt>
     Atenção!
    </dt>
    <dd>
     Seu navegador não pode executar javascript. Alguns recursos podem não funcionar corretamente.
    </dd>
   </dl>
  </noscript>
  <!-- modal session message -->
  <!-- User -->
  <!-- Header -->
  <!--
    Para habilitar o novo menu &#233; necess&#225;rio descoment&#225;-lo em:
    govbr/institucional/viewlets/institucional_menu_govbr.pt
    -->
  <!-- <header id="site-header" class="has-navigation-swipe"> -->
  <header class="has-navigation-dropdown" id="site-header" style="z-index: 999;">
   <div class="header-wrapper secondary">
    <barra-govbr class="width100 shadow-none show-contrast-toggle" contrastactive="false" id="barra-govbr" idiomaativo="" idiomas="" linklogo="https://www.gov.br/pt-br" linksdosistema='[{"title":"Órgãos do Governo","href":"https://www.gov.br/pt-br/orgaos-do-governo"},{"title":"Acesso à Informação","href":"https://www.gov.br/acessoainformacao/pt-br"},{"title":"Legislação","href":"http://www4.planalto.gov.br/legislacao"},{"title":"Acessibilidade","href":"https://www.gov.br/governodigital/pt-br/acessibilidade-digital"}]' linktitulo="https://www.gov.br/fazenda" signinhref="/govbrportal/inicializacao-autenticacao-openid.html" signouthref="/govbrportal/logout.html" style="width: 100%;" titulo="Ministério da Fazenda">
    </barra-govbr>
   </div>
   <div class="main">
    <div class="header-wrapper">
     <div class="site-name-wrapper">
      <a class="ico-navegacao toggle-main-navigation" href="#">
       <span class="sr-only">
        Abrir menu principal de navegação
       </span>
       <span aria-hidden="true" class="fa fa-bars">
       </span>
       <span aria-hidden="true" class="fa fa-times">
       </span>
      </a>
      <!-- <a href="/" class="site-name">Nome do site</a> -->
      <!-- Usar nome completo -->
      <div class="site-name">
       <a href="https://www.gov.br/receitafederal/pt-br">
        Receita Federal
       </a>
      </div>
     </div>
     <div class="termos-mais-buscados desktop">
      <section class="source-termos-mais-buscados">
       <div class="source-header-termos-mais-buscados">
        Termos mais buscados
       </div>
       <ul class="list-termos-mais-buscados">
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=imposto de renda">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          imposto de renda
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=inss">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          inss
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=assinatura">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          assinatura
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=cnh social">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          cnh social
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=enem">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          enem
         </a>
        </li>
       </ul>
      </section>
     </div>
     <div class="termos-mais-buscados mobile">
      <section class="source-termos-mais-buscados">
       <div class="source-header-termos-mais-buscados">
        Termos mais buscados
       </div>
       <ul class="list-termos-mais-buscados">
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=imposto de renda">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          imposto de renda
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=inss">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          inss
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=assinatura">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          assinatura
         </a>
        </li>
       </ul>
      </section>
     </div>
     <div class="govbr-busca-header">
      <div id="govbr-busca-input">
      </div>
     </div>
     <script>
      $(document).ready(function() {
                        $('#searchtext-label button').appendTo(".aa-InputWrapperPrefix");
                        $('#searchtext-label').remove();
                    });
     </script>
    </div>
   </div>
   <!-- Main Menu -->
   <nav aria-label="Menu Principal" class="navigation-wrapper navigation-dropdown">
    <div class="navigation-content">
     <div class="navigation-cell" id="main-navigation">
      <ul class="list-navigation">
       <li class="plain dropdown-submenu">
        <a class="plain" href="https://www.gov.br/receitafederal/pt-br/servicos">
         Serviços
        </a>
        <ul class="submenu">
         <li>
          <a class="state-published" href="https://www.gov.br/pt-br/orgaos/secretaria-especial-da-receita-federal-do-brasil">
           Serviços de A a Z
          </a>
         </li>
         <li class="dropdown-submenu">
          <a class="state-published hasDropDown" href="https://www.gov.br/receitafederal/pt-br/servicos/auditorias-fiscais">
           Auditorias Fiscais
          </a>
          <ul class="submenu navTree navTreeLevel1">
           <li>
            <a class="state-published" href="https://www.gov.br/receitafederal/pt-br/servicos/auditorias-fiscais/consultar-procedimentos-fiscais">
             Consultar procedimentos fiscais
            </a>
           </li>
           <li>
            <a class="state-published" href="https://www.gov.br/receitafederal/pt-br/servicos/auditorias-fiscais/responder-notificacoes">
             Responder notificações
            </a>
           </li>
           <li>
            <a class="state-published" href="https://www.gov.br/receitafederal/pt-br/servicos/auditorias-fiscais/obter-laudo-fiscal">
             Obter laudo fiscal
            </a>
           </li>
          </ul>
         </li>
         <li class="dropdown-submenu">
          <a class="state-published hasDropDown" href="https://www.gov.br/receitafederal/pt-br/servicos/cadastro">
           Cadastros
          </a>
          <ul class="submenu navTree navTreeLevel1">
           <li>
            <a class="state-published" href="https://www.gov.br/receitafederal/pt-br/servicos/cadastro/cidadao">
             Cidadão (CPF/CAEPF)
            </a>
           </li>
           <li>

bs4.BeautifulSoup

In [55]:
# Extraindo o link dos meses
links_meses = []
for a in soup.find_all('a', href=True):
    if f"/{ano_selecionado}/" in a['href'] and any(mes in a['href'] for mes in ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro']):
        links_meses.append(a['href'])
links_meses

['https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/abril',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/maio',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/junho',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/julho',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/agosto',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/setembro',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro']

In [56]:
url_com_ano

'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025'

In [57]:
links_meses = [
        a['href'] for a in soup.find_all('a', href=True)
        if a['href'].startswith(f"{url_com_ano}/") and any(m in a['href'] for m in ['janeiro', 'fevereiro', 'marco', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'])
    ]
links_meses

['https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/marco',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/abril',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/maio',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/junho',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/julho',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/agosto',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/setembro',
 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro']

In [58]:
# Preciso agora pegar os links das datas com os eventos em cada mes
print(links_meses[0])
## Vou pegar manualmente o primeiro mes
response = requests.get(links_meses[0])
print(f"URL sendo testada: {response.url}\nStatus code: {response.status_code}\n")
response.status_code
soup = BeautifulSoup(response.content, 'html.parser')
print(soup.prettify())

https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro
URL sendo testada: https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro
Status code: 200

<!DOCTYPE html>
<html lang="pt-br" xml:lang="pt-br" xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta charset="utf-8"/>
  <!-- Google Tag Manager -->
  <script type="text">
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-NHZSKTD');
  </script>
  <!-- End Google Tag Manager -->
  <script type="application/ld+json">
   {
            "@context": "https://schema.org",
            "@type": "Organization",
            "url": "https://www.gov.br/receitafederal",
            "logo": "https://www.gov.br/receitafederal/logo.png"
        }
  </script>
  <script type="application/ld+json">
   {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "url": "https://www.gov.br/receitafederal",
            "potentialAction": {
              "@type": "SearchAction",
              "target": "https://www.gov.br/receitafederal/search?SearchableText={search_term_string}",
              "query-input": "required name=search_term_string"
            }
        }
  </script>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <base href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/Janeiro/"/>
  <!--[if lt IE 7]></base><![endif]-->
  <meta content="Agenda Tributária" property="og:title"/>
  <meta content="Nesta seção estão disponíveis os prazos e vencimentos das obrigações tributárias por mês." property="og:description"/>
  <meta content="article" property="og:type"/>
  <meta content="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/Janeiro" property="og:url"/>
  <meta content="https://www.gov.br/receitafederal/logo.png" property="og:image"/>
  <meta content="pt_BR" property="og:locale"/>
  <meta content="Receita Federal " property="og:site_name"/>
  <script type="text">
   (function() {
        var po = document.createElement('script');
        po.async = true;
        po.src = document.location.protocol + '//connect.facebook.net/pt_BR/all.js#xfbml=1';
        var head = document.getElementsByTagName('head')[0];
        head.appendChild(po);
    }());
  </script>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="@" name="twitter:site"/>
  <meta content="Nesta seção estão disponíveis os prazos e vencimentos das obrigações tributárias por mês." name="description"/>
  <meta content="https://www.gov.br/fazenda" property="creator.productor"/>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/reset-cachekey-42de820bc50f17406b0f01f7602d9b79.css" media="screen" rel="stylesheet" type="text/css"/>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/base-cachekey-1991302562972620f08e052a97c8b5e1.css" rel="stylesheet" type="text/css"/>
  <style media="screen" type="text/css">
   @import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourceplone.app.jquerytools.dateinput-cachekey-5a249b5311d2f378428c7e7be2f636ff.css);
  </style>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourceplone.formwidget.datetimestyles-cachekey-e28848a3f2f551ef01b9a0b81d2fcf30.css" rel="stylesheet" type="text/css"/>
  <style media="screen" type="text/css">
   @import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/jquery.autocomplete-cachekey-a440e9cfa98b4dec71dc267a87964c31.css);
  </style>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/embedder-cachekey-f5e1139b55bdafccb135ab4042abec8c.css" media="screen" rel="stylesheet" type="text/css"/>
  <style media="screen" type="text/css">
   @import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcecollective.pollscsscollective.polls-cachekey-d5f72fea2e3f68069023c1f19c483d22.css);
  </style>
  <!--[if lt IE 8]>

    <link rel="stylesheet" type="text/css" href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/IEFixes-cachekey-0793ce9d8be480e2ed0228e3227efde7.css" media="screen" />
        <![endif]-->
  <style media="all" type="text/css">
   @import url(https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcepas.plugins.loginunicologinunico-cachekey-b0b1178bffe5161af33204d32599ecbf.css);
  </style>
  <link href="//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/css/swiper.min.css" media="screen" rel="stylesheet" type="text/css"/>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcelgpd.plugindsgov.min-cachekey-618c7f80ce75c9a81f6a4b657dcb1075.css" media="screen" rel="stylesheet" type="text/css"/>
  <link href="https://www.gov.br/receitafederal/portal_css/Sunburst%20Theme/resourcegovbr.policycanais-cachekey-2f2ee33639add88e0a00d1df7cf7488c.css" rel="stylesheet" type="text/css"/>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policybrowser-update-cachekey-63c70a22490b29beaad3085901a45ea3.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourceplone.app.jquery-cachekey-3c746bb4a983838f10cdc0926e9ed66a.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policyfolder_contents-cachekey-884e305b01ef76397df4508c707ededd.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policycookiebar_1_3_55-cachekey-e5d51de04e2fcf108fd0e1bf692c8160.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcegovbr.policyapplication_cookiebar_1_3_55-cachekey-8a32efed0b2a01ba33c19f2fd57ebf22.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/collective.js.jqueryui.custom.min-cachekey-c838bf037d3098390e48cde4b3eecd77.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourceplone.formwidget.recurrencejquery.tmpl-beta1-cachekey-70b23b5b387b6e7a9a03062836d1e235.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcecollective.js.bootstrapjsbootstrap.min-cachekey-11a00508837ff5d5907db69871e85ef3.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcecollective.coverjsmain-cachekey-88bef20151707ed848d6bb4cffdb8872.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcebrasil.gov.tilesvendorjquery.jplayer.min-cachekey-25cea8128c136f33a70e2ed1dacc5eb5.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcedropdown-menu-cachekey-3d8e116f2145631124393316d3d52e37.js" type="text/javascript">
  </script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.min.js" type="text/javascript">
  </script>
  <script type="text/javascript">
  </script>
  <script type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcelgpd.pluginchangeCookieImage-cachekey-52453a911ff2b5c2e7b019805f3ec46f.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/resourcelgpd.pluginblock_cookies-cachekey-171f4aba329dae4ab47afc814ab9e0f2.js" type="text/javascript">
  </script>
  <script src="https://www.gov.br/receitafederal/portal_javascripts/Sunburst%20Theme/++resource++govbr.recomendacao/govbr.recom.12bf697a4cb12043ba4c.js" type="text/javascript">
  </script>
  <link href="https://www.gov.br/receitafederal/++resource++brasil.gov.agenda/brasilgovagenda-720c34e.css" rel="stylesheet"/>
  <script defer="defer" src="https://www.gov.br/receitafederal/++resource++brasil.gov.agenda/brasilgovagenda-720c34e.js">
  </script>
  <link href="https://www.gov.br/receitafederal/++resource++brasil.gov.portal/brasilgovportal-ee510e4.css" rel="stylesheet"/>
  <script defer="defer" src="https://www.gov.br/receitafederal/++resource++brasil.gov.portal/brasilgovportal-ee510e4.js">
  </script>
  <link href="https://www.gov.br/receitafederal/++resource++brasil.gov.tiles/brasilgovtiles-7d5753d.css" rel="stylesheet"/>
  <script defer="defer" src="https://www.gov.br/receitafederal/++resource++brasil.gov.tiles/brasilgovtiles-7d5753d.js">
  </script>
  <title>
   Agenda Tributária — Receita Federal
  </title>
  <link href="http://vocab.e.gov.br/2011/03/vcge#esquema" rel="http://purl.org/dc/terms/subject http://schema.org/about http://xmlns.com/foaf/0.1/primaryTopic"/>
  <link href="https://www.gov.br/receitafederal/pt-br" rel="author" title="Informações do Autor"/>
  <link href="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro" rel="canonical"/>
  <script type="text/javascript">
   jQuery(function($){
            if (typeof($.datepicker) != "undefined"){
              $.datepicker.setDefaults(
                jQuery.extend($.datepicker.regional['pt-BR'],
                {dateFormat: 'dd/mm/yy'}));
            }
        });
  </script>
  <link href="https://www.gov.br/receitafederal/pt-br/@@search" rel="search" title="Buscar neste site"/>
  <meta content="Plone - http://plone.org" name="generator"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="/receitafederal/++theme++padrao_govbr/favicons/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
  <link href="/receitafederal/++theme++padrao_govbr/favicons/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
  <link href="/receitafederal/++theme++padrao_govbr/favicons/favicon-48x48.png" rel="shortcut icon" type="image/png"/>
  <link color="#00a300" href="/receitafederal/++theme++padrao_govbr/favicons/safari-pinned-tab.svg" rel="mask-icon"/>
  <meta content="favicons/browserconfig.xml" name="msapplication-config"/>
  <meta content="#00a300" name="theme-color"/>
  <link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" referrerpolicy="no-referrer" rel="stylesheet"/>
  <style>
   body.userrole-authenticated .btn.btn-success.fileinput-button span:after {
            content: "Adicionar Arquivos" !important;
        }
  </style>
  <script id="barra-govbr-pro" src="https://barra.sistema.gov.br/v1/barra-govbr-wc.iife.js" type="module">
  </script>
  <script defer="defer" src="/govbrportal/js/session.js" type="module">
  </script>
  <link href="/receitafederal/++theme++padrao_govbr/govbrtheme-8fb61a6.css" rel="stylesheet"/>
 </head>
 <body class="default-header-template portal-institucional cover-layout-layout-vazio template-standard portaltype-collective-cover-content site-pt-br section-assuntos subsection-agenda-tributaria subsection-agenda-tributaria-2025 subsection-agenda-tributaria-2025-janeiro userrole-anonymous" data-base-url="https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/Janeiro" data-portal-url="https://www.gov.br/receitafederal" dir="ltr" id="">
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe data-src="https://www.googletagmanager.com/ns.html?id=GTM-NHZSKTD" height="0" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <nav aria-label="Acesso rápido" class="govbr-skip-menu">
   <a accesskey="1" href="#wrapper">
    <span class="sr-only">
     Ir para o
    </span>
    Conteúdo
    <span class="access-key">
     1
    </span>
   </a>
   <a accesskey="2" href="/">
    <span class="sr-only">
     Ir para a
    </span>
    Página Inicial
    <span class="access-key">
     2
    </span>
   </a>
   <a accesskey="3" href="#main-navigation">
    <span class="sr-only">
     Ir para o menu de
    </span>
    Navegação
    <span class="access-key">
     3
    </span>
   </a>
   <a accesskey="4" href="#govbr-busca-input">
    <span class="sr-only">
     Ir para a
    </span>
    Busca
    <span class="access-key">
     4
    </span>
   </a>
   <a accesskey="5" href="#portal-footer">
    <span class="sr-only">
     Ir para o
    </span>
    Mapa do site
    <span class="access-key">
     5
    </span>
   </a>
  </nav>
  <noscript aria-label="Aviso de Javascript desabilitado">
   <dl class="portalMessage attention erro-javascript">
    <dt>
     Atenção!
    </dt>
    <dd>
     Seu navegador não pode executar javascript. Alguns recursos podem não funcionar corretamente.
    </dd>
   </dl>
  </noscript>
  <!-- modal session message -->
  <!-- User -->
  <!-- Header -->
  <!--
    Para habilitar o novo menu &#233; necess&#225;rio descoment&#225;-lo em:
    govbr/institucional/viewlets/institucional_menu_govbr.pt
    -->
  <!-- <header id="site-header" class="has-navigation-swipe"> -->
  <header class="has-navigation-dropdown" id="site-header" style="z-index: 999;">
   <div class="header-wrapper secondary">
    <barra-govbr class="width100 shadow-none show-contrast-toggle" contrastactive="false" id="barra-govbr" idiomaativo="" idiomas="" linklogo="https://www.gov.br/pt-br" linksdosistema='[{"title":"Órgãos do Governo","href":"https://www.gov.br/pt-br/orgaos-do-governo"},{"title":"Acesso à Informação","href":"https://www.gov.br/acessoainformacao/pt-br"},{"title":"Legislação","href":"http://www4.planalto.gov.br/legislacao"},{"title":"Acessibilidade","href":"https://www.gov.br/governodigital/pt-br/acessibilidade-digital"}]' linktitulo="https://www.gov.br/fazenda" signinhref="/govbrportal/inicializacao-autenticacao-openid.html" signouthref="/govbrportal/logout.html" style="width: 100%;" titulo="Ministério da Fazenda">
    </barra-govbr>
   </div>
   <div class="main">
    <div class="header-wrapper">
     <div class="site-name-wrapper">
      <a class="ico-navegacao toggle-main-navigation" href="#">
       <span class="sr-only">
        Abrir menu principal de navegação
       </span>
       <span aria-hidden="true" class="fa fa-bars">
       </span>
       <span aria-hidden="true" class="fa fa-times">
       </span>
      </a>
      <!-- <a href="/" class="site-name">Nome do site</a> -->
      <!-- Usar nome completo -->
      <div class="site-name">
       <a href="https://www.gov.br/receitafederal/pt-br">
        Receita Federal
       </a>
      </div>
     </div>
     <div class="termos-mais-buscados desktop">
      <section class="source-termos-mais-buscados">
       <div class="source-header-termos-mais-buscados">
        Termos mais buscados
       </div>
       <ul class="list-termos-mais-buscados">
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=imposto de renda">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          imposto de renda
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=inss">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          inss
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=assinatura">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          assinatura
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=cnh social">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          cnh social
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=enem">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          enem
         </a>
        </li>
       </ul>
      </section>
     </div>
     <div class="termos-mais-buscados mobile">
      <section class="source-termos-mais-buscados">
       <div class="source-header-termos-mais-buscados">
        Termos mais buscados
       </div>
       <ul class="list-termos-mais-buscados">
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=imposto de renda">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          imposto de renda
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=inss">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          inss
         </a>
        </li>
        <li class="item-termos-mais-buscados">
         <a href="https://www.gov.br/receitafederal/pt-br/search?origem=termos&amp;SearchableText=assinatura">
          <span class="fa-solid fa-arrow-trend-up">
          </span>
          assinatura
         </a>
        </li>
       </ul>
      </section>
     </div>
     <div class="govbr-busca-header">
      <div id="govbr-busca-input">
      </div>
     </div>
     <script>
      $(document).ready(function() {
                        $('#searchtext-label button').appendTo(".aa-InputWrapperPrefix");
                        $('#searchtext-label').remove();
                    });
     </script>
    </div>
   </div>
   <!-- Main Menu -->
   <nav aria-label="Menu Principal" class="navigation-wrapper navigation-dropdown">
    <div class="navigation-content">
     <div class="navigation-cell" id="main-navigation">
      <ul class="list-navigation">
       <li class="plain dropdown-submenu">
        <a class="plain" href="https://www.gov.br/receitafederal/pt-br/servicos">
         Serviços
        </a>
        <ul class="submenu">
         <li>
          <a class="state-published" href="https://www.gov.br/pt-br/orgaos/secretaria-especial-da-receita-federal-do-brasil">
           Serviços de A a Z
          </a>
         </li>
         <li class="dropdown-submenu">
          <a class="state-published hasDropDown" href="https://www.gov.br/receitafederal/pt-br/servicos/auditorias-fiscais">
           Auditorias Fiscais
          </a>
          <ul class="submenu navTree navTreeLevel1">
           <li>
            <a class="state-published" href="https://www.gov.br/receitafederal/pt-br/servicos/auditorias-fiscais/consultar-procedimentos-fiscais">
             Consultar procedimentos fiscais
            </a>
           </li>
           <li>
            <a class="state-published" href="https://www.gov.br/receitafederal/pt-br/servicos/auditorias-fiscais/responder-notificacoes">
             Responder notificações
            </a>
           </li>
           <li>
            <a class="state-published" href="https://www.gov.br/receitafederal/pt-br/servicos/auditorias-fiscais/obter-laudo-fiscal">
             Obter laudo fiscal
            </a>
           </li>
          </ul>
         </li>
         <li class="dropdown-submenu">
          <a class="state-published hasDropDown" href="https://www.gov.br/receitafederal/pt-br/servicos/cadastro">
           Cadastros
          </a>

In [59]:
print(response.url)
# janeiro
links_datas = []
for a in soup.select('a'):
    if a['href'].startswith(response.url) and '/dia-' in a['href']:
        links_datas.append(a['href'])

print(len(links_datas))
print(links_datas)

https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro
10
['https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025', 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-08-01-2025', 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-10-01-2025', 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-15-01-2025', 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-20-01-2025', 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-22-01-2025', 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-23-01-2025', 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-24-01-2025', 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-27-01-2025', 'https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-31-01-2025']

In [60]:
# Dicionário para armazenar os dados
dados_agenda = {}
nome_mes = 'janeiro'
dados_agenda[nome_mes] = {}
print(dados_agenda)

{'janeiro': {}}

In [61]:
for link_data in links_datas:
    nome_data = link_data.split('/')[-1]  # Extrai o nome da data do link
    print(nome_data)
    url_data = link_data
    print(url_data)
    response = requests.get(url_data)
    soup = BeautifulSoup(response.content, 'html.parser')
    tabelas_html = soup.find_all('table')
    tabelas = []
    for tabela in tabelas_html:
        df = pd.read_html(StringIO(str(tabela)))[0]  # Corrigido
        tabelas.append(df.to_dict(orient='records'))
    dados_agenda[nome_mes][nome_data] = tabelas
    print(dados_agenda)

dia-06-01-2025
https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
{'janeiro': {'dia-06-01-2025': [[{'Código DARF': 8053, 'Descrição do tributo/contribuição': 'IRRF - Títulos de Renda Fixa - Pessoa Física', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 3426, 'Descrição do tributo/contribuição': 'IRRF - Títulos de Renda Fixa - Pessoa Jurídica', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 6800, 'Descrição do tributo/contribuição': 'IRRF -\xa0Fundo de Investimento sujeito à tributação periódica', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 6813, 'Descrição do tributo/contribuição': 'IRRF - Fundo de Investimento em Ações', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5273, 'Descrição do tributo/contribuição': 'IRRF - Operações de SWAP', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 8468, 'Descrição do tributo/contribuição': 'IRRF - Day-Trade - Operações em Bolsas', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5557, 'Descrição do tributo/contribuição': 'IRRF - Ganhos líquidos em operações em bolsas e assemelhados', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5706, 'Descrição do tributo/contribuição': 'IRPF - Juros remuneratórios do capital próprio (art. 9º da Lei nº 9.249/95)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5232, 'Descrição do tributo/contribuição': 'IRRF -\xa0Fundos de Investimento Imobiliário (FII) e Fundos de Investimento nas Cadeias Produtivas do Agronegócio (Fiagro) - Resgate ou amortização de cotas ou distribuição de rendimentos', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 924, 'Descrição do tributo/contribuição': 'IRRF - Demais rendimentos de capital', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 3699, 'Descrição do tributo/contribuição': 'IRRF -\xa0Aplicações financeiras em ativos de infraestrutura - Tributação Exclusiva', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5029, 'Descrição do tributo/contribuição': 'IRRF - Ganho de Capital - Integralização de Cotas com Ativos (art. 1º da Lei nº 13.043/2014)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5035, 'Descrição do tributo/contribuição': 'IRRF -\xa0Fundos de Investimento - Lei nº 13.043/2014 (Art. 8º) e Lei nº 14.801/2024 (Art. 4º)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1605, 'Descrição do tributo/contribuição': 'IRRF -\xa0Fundo de Investimento em Participações (FIP), Fundo de Investimento em Índice de Mercado (Exchange Traded Fund - ETF), Fundo de Investimento em Direitos Creditórios (FIDC) e Fundo Multimercado (FIM)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5286, 'Descrição do tributo/contribuição': 'IRRF - Aplicações Financeiras', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 9453, 'Descrição do tributo/contribuição': 'IRRF - Juros remuneratórios de capital próprio', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 916, 'Descrição do tributo/contribuição': 'IRRF - Prêmios obtidos em concursos e sorteios', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 8673, 'Descrição do tributo/contribuição': 'IRRF - Prêmios obtidos em Bingos', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 9385, 'Descrição do tributo/contribuição': 'IRRF - Multas e vantagens', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1150, 'Descrição do tributo/contribuição': 'IOF - Operações Crédito - Pessoa Jurídica', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 7893, 'Descrição do tributo/contribuição': 'IOF - Operações Crédito - Pessoa Física', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 4290, 'Descrição do tributo/contribuição': 'IOF - Operações de Câmbio - Entrada de moeda', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5220, 'Descrição do tributo/contribuição': 'IOF - Operações de Câmbio - Saída de moeda', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 6854, 'Descrição do tributo/contribuição': 'IOF - Aplicações Financeiras', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 6895, 'Descrição do tributo/contribuição': 'IOF - Factoring (art. 58 da Lei nº 9.532/97)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 3467, 'Descrição do tributo/contribuição': 'IOF - Seguros', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 4028, 'Descrição do tributo/contribuição': 'IOF - Ouro, Ativo Financeiro', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1661, 'Descrição do tributo/contribuição': 'CPSS - Servidor Civil Ativo', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1700, 'Descrição do tributo/contribuição': 'CPSS - Servidor Civil Inativo', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1717, 'Descrição do tributo/contribuição': 'CPSS - Pensionista Civil', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1769, 'Descrição do tributo/contribuição': 'CPSS - Patronal - Servidor Civil Ativo - Operação Intra-Orçamentária', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1814, 'Descrição do tributo/contribuição': 'CPSS - Patronal - Servidor no Exterior - Operação Intra-Orçamentária', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1723, 'Descrição do tributo/contribuição': 'CPSS - Servidor Civil Ativo - Precatório Judicial e Requisição de Pequeno Valor', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1730, 'Descrição do tributo/contribuição': 'CPSS - Servidor Civil Inativo - Precatório Judicial e Requisição de Pequeno Valor', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1752, 'Descrição do tributo/contribuição': 'CPSS - Pensionista - Precatório Judicial e Requisição de Pequeno Valor', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}]]}}
dia-08-01-2025
https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-08-01-2025
{'janeiro': {'dia-06-01-2025': [[{'Código DARF': 8053, 'Descrição do tributo/contribuição': 'IRRF - Títulos de Renda Fixa - Pessoa Física', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 3426, 'Descrição do tributo/contribuição': 'IRRF - Títulos de Renda Fixa - Pessoa Jurídica', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 6800, 'Descrição do tributo/contribuição': 'IRRF -\xa0Fundo de Investimento sujeito à tributação periódica', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 6813, 'Descrição do tributo/contribuição': 'IRRF - Fundo de Investimento em Ações', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5273, 'Descrição do tributo/contribuição': 'IRRF - Operações de SWAP', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 8468, 'Descrição do tributo/contribuição': 'IRRF - Day-Trade - Operações em Bolsas', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5557, 'Descrição do tributo/contribuição': 'IRRF - Ganhos líquidos em operações em bolsas e assemelhados', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5706, 'Descrição do tributo/contribuição': 'IRPF - Juros remuneratórios do capital próprio (art. 9º da Lei nº 9.249/95)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5232, 'Descrição do tributo/contribuição': 'IRRF -\xa0Fundos de Investimento Imobiliário (FII) e Fundos de Investimento nas Cadeias Produtivas do Agronegócio (Fiagro) - Resgate ou amortização de cotas ou distribuição de rendimentos', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 924, 'Descrição do tributo/contribuição': 'IRRF - Demais rendimentos de capital', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 3699, 'Descrição do tributo/contribuição': 'IRRF -\xa0Aplicações financeiras em ativos de infraestrutura - Tributação Exclusiva', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5029, 'Descrição do tributo/contribuição': 'IRRF - Ganho de Capital - Integralização de Cotas com Ativos (art. 1º da Lei nº 13.043/2014)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5035, 'Descrição do tributo/contribuição': 'IRRF -\xa0Fundos de Investimento - Lei nº 13.043/2014 (Art. 8º) e Lei nº 14.801/2024 (Art. 4º)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1605, 'Descrição do tributo/contribuição': 'IRRF -\xa0Fundo de Investimento em Participações (FIP), Fundo de Investimento em Índice de Mercado (Exchange Traded Fund - ETF), Fundo de Investimento em Direitos Creditórios (FIDC) e Fundo Multimercado (FIM)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5286, 'Descrição do tributo/contribuição': 'IRRF - Aplicações Financeiras', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 9453, 'Descrição do tributo/contribuição': 'IRRF - Juros remuneratórios de capital próprio', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 916, 'Descrição do tributo/contribuição': 'IRRF - Prêmios obtidos em concursos e sorteios', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 8673, 'Descrição do tributo/contribuição': 'IRRF - Prêmios obtidos em Bingos', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 9385, 'Descrição do tributo/contribuição': 'IRRF - Multas e vantagens', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1150, 'Descrição do tributo/contribuição': 'IOF - Operações Crédito - Pessoa Jurídica', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 7893, 'Descrição do tributo/contribuição': 'IOF - Operações Crédito - Pessoa Física', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 4290, 'Descrição do tributo/contribuição': 'IOF - Operações de Câmbio - Entrada de moeda', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 5220, 'Descrição do tributo/contribuição': 'IOF - Operações de Câmbio - Saída de moeda', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 6854, 'Descrição do tributo/contribuição': 'IOF - Aplicações Financeiras', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 6895, 'Descrição do tributo/contribuição': 'IOF - Factoring (art. 58 da Lei nº 9.532/97)', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 3467, 'Descrição do tributo/contribuição': 'IOF - Seguros', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 4028, 'Descrição do tributo/contribuição': 'IOF - Ouro, Ativo Financeiro', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1661, 'Descrição do tributo/contribuição': 'CPSS - Servidor Civil Ativo', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1700, 'Descrição do tributo/contribuição': 'CPSS - Servidor Civil Inativo', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1717, 'Descrição do tributo/contribuição': 'CPSS - Pensionista Civil', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1769, 'Descrição do tributo/contribuição': 'CPSS - Patronal - Servidor Civil Ativo - Operação Intra-Orçamentária', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1814, 'Descrição do tributo/contribuição': 'CPSS - Patronal - Servidor no Exterior - Operação Intra-Orçamentária', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1723, 'Descrição do tributo/contribuição': 'CPSS - Servidor Civil Ativo - Precatório Judicial e Requisição de Pequeno Valor', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1730, 'Descrição do tributo/contribuição': 'CPSS - Servidor Civil Inativo - Precatório Judicial e Requisição de Pequeno Valor', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}, {'Código DARF': 1752, 'Descrição do tributo/contribuição': 'CPSS - Pensionista - Precatório Judicial e Requisição de Pequeno Valor', 'Período do Fato Gerador': '21 a 31/dezembro/2024'}]], 'dia-08-01-2025': [[{'Código GPS': 7307, 'Descrição do tributo/contribuição': 'Comprev - recolhimento efetuado por RPPS - órgão do poder público - CNPJ', 'Período do Fato Gerador': '1º a 30/novembro/2024'}, {'Código GPS': 7315, 'Descrição do tributo/contribuição': 'Comprev - recolhimento efetuado por RPPS - órgão do poder público - CNPJ - estoque', 'Período do Fato Gerador': '1º a 30/novembro/2024'}]]}}
dia-10-01-2025
https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-10-01-2025

### Verificando possíveis tratamentos para o json

In [62]:
import pandas as pd

In [63]:
# Carregando os dados salvos
ano_selecionado = 2025
df_base = pd.read_json(f'../data/transformed/agenda_tributaria_{ano_selecionado}.json')
df_base.head()

                                                                             fonte extraido_em   ano  \
janeiro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025  2025-10-02  2025
fevereiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025  2025-10-02  2025
marco      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025  2025-10-02  2025
abril      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025  2025-10-02  2025
maio       https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025  2025-10-02  2025


In [64]:
df_base.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, janeiro to outubro
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   fonte        10 non-null     object
 1   extraido_em  10 non-null     object
 2   ano          10 non-null     int64
 3   meses        10 non-null     object
dtypes: int64(1), object(3)
memory usage: 400.0+ bytes

In [65]:
import json
import pandas as pd
from datetime import datetime

# Passo 1: Carregar o JSON do seu arquivo
with open(f'../data/transformed/agenda_tributaria_{ano_selecionado}.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Lista para armazenar todos os eventos
eventos_com_urls = []

# Passo 2: Iterar sobre a estrutura aninhada e extrair os dados, incluindo as URLs
for mes_nome, mes_info in data['meses'].items():
    mes_url = mes_info['url']  # URL do Mês
    
    for dia_chave, dia_info in mes_info['dias'].items():
        dia_url = dia_info['url']  # URL do Dia
        
        # Extrair a data do nome da chave
        data_str = dia_chave.replace('dia-', '')
        data_evento = datetime.strptime(data_str, '%d-%m-%Y').strftime('%Y-%m-%d')
        
        # Iterar sobre a lista de eventos de cada dia
        for evento in dia_info['eventos']:
            
            # Adicionar a data e as URLs ao dicionário de cada evento
            evento_com_meta = evento.copy()  # Cria uma cópia para não modificar o dicionário original
            evento_com_meta['data_evento'] = data_evento
            evento_com_meta['mes_url'] = mes_url
            evento_com_meta['dia_url'] = dia_url
            eventos_com_urls.append(evento_com_meta)

# Passo 3: Criar um DataFrame com os dados transformados e as URLs
df = pd.DataFrame(eventos_com_urls)

# Passo 4: Realizar as transformações finais no DataFrame
df.rename(columns={
    'descricao': 'descricao',
    'tipo': 'tipo',
    'codigo_darf': 'codigo_darf',
    'codigo_gps': 'codigo_gps',
    'documento': 'documento',
    'periodo_fato_gerador': 'periodo_fato_gerador',
    'data_evento': 'data_evento'
}, inplace=True)

# Reordenar as colunas para melhor visualização (opcional)
colunas_ordenadas = [
    'data_evento', 'dia_url', 'mes_url', 'tipo', 'descricao', 
    'codigo_darf', 'codigo_gps', 'documento', 'periodo_fato_gerador'
]
df = df[colunas_ordenadas]

# Preencher valores 'null' ou nulos com None para inserção no SQL
df = df.where(pd.notnull(df), None)

# Exibir o DataFrame para verificar o resultado
df.head()

  data_evento                                                                                         dia_url                                                                          mes_url  tipo                                                    descricao codigo_darf codigo_gps documento   periodo_fato_gerador
0  2025-01-06  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  darf                 IRRF - Títulos de Renda Fixa - Pessoa Física        8053       None      None  21 a 31/dezembro/2024
1  2025-01-06  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  darf               IRRF - Títulos de Renda Fixa - Pessoa Jurídica        3426       None      None  21 a 31/dezembro/2024
2  2025-01-06  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  darf  IRRF - Fundo de Investimento sujeito à tributação periódica        6800       None      None  21 a 31/dezembro/2024
3  2025-01-06  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  darf                        IRRF - Fundo de Investimento em Ações        6813       None      None  21 a 31/dezembro/2024
4  2025-01-06  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  darf                                     IRRF - Operações de SWAP        5273       None      None  21 a 31/dezembro/2024

In [66]:
import json
import pandas as pd
from datetime import datetime
from IPython.display import display

# Passo 1: Carregar o JSON do seu arquivo
# Abre o arquivo JSON e o carrega para uma variável Python
with open(f'../data/transformed/agenda_tributaria_{ano_selecionado}.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Lista para armazenar todos os eventos "aplanados"
eventos_com_urls = []

# Passo 2: Iterar sobre a estrutura aninhada e extrair os dados e URLs
# Itera sobre os meses do JSON
for mes_nome, mes_info in data['meses'].items():
    # Extrai a URL do mês
    mes_url = mes_info['url']
    
    # Itera sobre os dias dentro de cada mês
    for dia_chave, dia_info in mes_info['dias'].items():
        # Extrai a URL do dia
        dia_url = dia_info['url']
        
        # Converte a chave do dia (ex: 'dia-06-01-2025') para o formato de data
        data_str = dia_chave.replace('dia-', '')
        data_evento = datetime.strptime(data_str, '%d-%m-%Y').strftime('%Y-%m-%d')
        
        # Itera sobre a lista de eventos de cada dia
        for evento in dia_info['eventos']:
            
            # Cria uma nova linha de dados (dicionário) com todas as informações
            evento_com_meta = evento.copy()
            evento_com_meta['data_evento'] = data_evento
            evento_com_meta['mes_url'] = mes_url
            evento_com_meta['dia_url'] = dia_url
            
            # Adiciona a nova linha à lista de eventos
            eventos_com_urls.append(evento_com_meta)

# Passo 3: Criar um DataFrame com os dados transformados
# Converte a lista de dicionários em um DataFrame do pandas
df = pd.DataFrame(eventos_com_urls)

# Passo 4: Realizar as transformações finais no DataFrame (opcional, mas recomendado)
# Renomeia as colunas para o padrão do banco de dados
df.rename(columns={
    'descricao': 'descricao',
    'tipo': 'tipo',
    'codigo_darf': 'codigo_darf',
    'codigo_gps': 'codigo_gps',
    'documento': 'documento',
    'periodo_fato_gerador': 'periodo_fato_gerador',
    'data_evento': 'data_evento'
}, inplace=True)

# Reordena as colunas para uma melhor visualização
colunas_ordenadas = [
    'data_evento', 'tipo', 'codigo_darf', 'codigo_gps', 'documento', 'descricao', 'periodo_fato_gerador','mes_url', 'dia_url'
]
df = df[colunas_ordenadas]

# Preenche os valores ausentes (NaN) com None, o que é ideal para o SQL
df = df.where(pd.notnull(df), None)

# Exibe o DataFrame pronto para ser inserido
display(df)

     data_evento           tipo codigo_darf codigo_gps documento                                                        descricao   periodo_fato_gerador                                                                          mes_url                                                                                         dia_url
0     2025-01-06           darf        8053       None      None                     IRRF - Títulos de Renda Fixa - Pessoa Física  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
1     2025-01-06           darf        3426       None      None                   IRRF - Títulos de Renda Fixa - Pessoa Jurídica  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
2     2025-01-06           darf        6800       None      None      IRRF - Fundo de Investimento sujeito à tributação periódica  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
3     2025-01-06           darf        6813       None      None                            IRRF - Fundo de Investimento em Ações  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
4     2025-01-06           darf        5273       None      None                                         IRRF - Operações de SWAP  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
...          ...            ...         ...        ...       ...                                                              ...                    ...                                                                              ...                                                                                             ...
3316  2025-10-31  declaracao_pj        None       None      None  DCTFWeb - Declaração de Débitos e Créditos Tributários Federais          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025
3317  2025-10-31  declaracao_pj        None       None      None    DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025
3318  2025-10-31  declaracao_pj        None       None      None                    DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025
3319  2025-10-31  declaracao_pf        None       None      None    DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025
3320  2025-10-31  declaracao_pf        None       None      None                    DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025

[3321 rows x 9 columns]

In [67]:
pd.set_option("display.max_colwidth", None)  # mostra texto completo
pd.set_option("display.width", 2000)         # aumenta largura da tabela
pd.set_option("display.max_columns", None)   # mostra todas as colunas
df[["descricao"]]

                                                            descricao
0                        IRRF - Títulos de Renda Fixa - Pessoa Física
1                      IRRF - Títulos de Renda Fixa - Pessoa Jurídica
2         IRRF - Fundo de Investimento sujeito à tributação periódica
3                               IRRF - Fundo de Investimento em Ações
4                                            IRRF - Operações de SWAP
...                                                               ...
3316  DCTFWeb - Declaração de Débitos e Créditos Tributários Federais
3317    DME - Declaração de Operações Liquidadas com Moeda em Espécie
3318                    DOI - Declaração sobre Operações Imobiliárias
3319    DME - Declaração de Operações Liquidadas com Moeda em Espécie
3320                    DOI - Declaração sobre Operações Imobiliárias

[3321 rows x 1 columns]

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3321 entries, 0 to 3320
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   data_evento           3321 non-null   object
 1   tipo                  3321 non-null   object
 2   codigo_darf           2707 non-null   object
 3   codigo_gps            410 non-null    object
 4   documento             80 non-null     object
 5   descricao             3321 non-null   object
 6   periodo_fato_gerador  3125 non-null   object
 7   mes_url               3321 non-null   object
 8   dia_url               3321 non-null   object
dtypes: object(9)
memory usage: 233.6+ KB

In [69]:
df["descricao"].unique()

array(['IRRF - Títulos de Renda Fixa - Pessoa Física',
       'IRRF - Títulos de Renda Fixa - Pessoa Jurídica',
       'IRRF -\xa0Fundo de Investimento sujeito à tributação periódica',
       'IRRF - Fundo de Investimento em Ações',
       'IRRF - Operações de SWAP',
       'IRRF - Day-Trade - Operações em Bolsas',
       'IRRF - Ganhos líquidos em operações em bolsas e assemelhados',
       'IRPF - Juros remuneratórios do capital próprio (art. 9º da Lei nº 9.249/95)',
       'IRRF -\xa0Fundos de Investimento Imobiliário (FII) e Fundos de Investimento nas Cadeias Produtivas do Agronegócio (Fiagro) - Resgate ou amortização de cotas ou distribuição de rendimentos',
       'IRRF - Demais rendimentos de capital',
       'IRRF -\xa0Aplicações financeiras em ativos de infraestrutura - Tributação Exclusiva',
       'IRRF - Ganho de Capital - Integralização de Cotas com Ativos (art. 1º da Lei nº 13.043/2014)',
       'IRRF -\xa0Fundos de Investimento - Lei nº 13.043/2014 (Art. 8º) e Lei nº 14.801/2024 (Art. 4º)',
       'IRRF -\xa0Fundo de Investimento em Participações (FIP), Fundo de Investimento em Índice de Mercado (Exchange Traded Fund - ETF), Fundo de Investimento em Direitos Creditórios (FIDC) e Fundo Multimercado (FIM)',
       'IRRF - Aplicações Financeiras',
       'IRRF - Juros remuneratórios de capital próprio',
       'IRRF - Prêmios obtidos em concursos e sorteios',
       'IRRF - Prêmios obtidos em Bingos', 'IRRF - Multas e vantagens',
       'IOF - Operações Crédito - Pessoa Jurídica',
       'IOF - Operações Crédito - Pessoa Física',
       'IOF - Operações de Câmbio - Entrada de moeda',
       'IOF - Operações de Câmbio - Saída de moeda',
       'IOF - Aplicações Financeiras',
       'IOF - Factoring (art. 58 da Lei nº 9.532/97)', 'IOF - Seguros',
       'IOF - Ouro, Ativo Financeiro', 'CPSS - Servidor Civil Ativo',
       'CPSS - Servidor Civil Inativo', 'CPSS - Pensionista Civil',
       'CPSS - Patronal - Servidor Civil Ativo - Operação Intra-Orçamentária',
       'CPSS - Patronal - Servidor no Exterior - Operação Intra-Orçamentária',
       'CPSS - Servidor Civil Ativo - Precatório Judicial e Requisição de Pequeno Valor',
       'CPSS - Servidor Civil Inativo - Precatório Judicial e Requisição de Pequeno Valor',
       'CPSS - Pensionista - Precatório Judicial e Requisição de Pequeno Valor',
       'Comprev - recolhimento efetuado por RPPS - órgão do poder público - CNPJ',
       'Comprev - recolhimento efetuado por RPPS - órgão do poder público - CNPJ - estoque',
       'IPI - Cigarros contendo Tabaco (Cigarros dos cód. 2402.20.00 da Tipi)',
       'IRRF - Outros Rendimentos - Juros de empréstimos externos',
       'Envio, pelo Município, da relação de todos os alvarás para construção civil e documentos de habite-se concedidos.',
       'IRRF - Juros remuneratórios do capital próprio (art 9º da Lei nº 9.249/95)',
       'IRRF - Fundo de Investimento em Participações (FIP), Fundo de Investimento em Índice de Mercado (Exchange Traded Fund - ETF), Fundo de Investimento em Direitos Creditórios (FIDC) e Fundo Multimercado (FIM)',
       'IOF - Operações de Crédito/Mútuo - Pessoa Jurídica',
       'IOF - Operações de Crédito/Mútuo - Pessoa Física',
       'PIS/PASEP - Retenção - Aquisição de autopeças',
       'COFINS - Retenção - Aquisição de autopeças',
       'CIDE - Combustíveis - Contribuição de Intervenção no Domínio Econômico incidente sobre a comercialização de petróleo e seus derivados, gás natural, exceto sob a forma liquefeita, e seus derivados, e álcool etílico combustível',
       'CIDE - Remessas ao Exterior - Contribuição de Intervenção no Domínio Econômico incidente sobre remessa de importâncias ao exterior nas hipóteses tratadas no art. 2º da Lei nº 10.168/2000,com a alteração introduzida pelo art. 6º da Lei nº 10.332/2001',
       'Contribuinte individual - recolhimento mensal NIT/PIS/Pasep',
       'Contribuinte individual - recolhimento mensal - com dedução de 45% (Lei nº 9.876/99) - NIT/PIS/Pasep',
       'Contribuinte Individual - Opção: aposentadoria apenas por idade- Recolhimento Mensal - NIT/PIS/PASEP',
       'Segurado Facultativo – recolhimento mensal – NIT /PIS /Pasep',
       'Facultativo - Opção: aposentadoria apenas por idade - Recolhimento Mensal - NIT/PIS/PASEP',
       'Segurado Especial – recolhimento mensal – NIT /PIS /Pasep',
       'Facultativo Baixa Renda - recolhimento mensal - Complemento para Plano Simplificado da Previdência Social - PSPS - Lei nº 12.470/2011',
       'MEI - Complentação Mensal',
       'Facultativo Baixa Renda - recolhimento mensal - NIT/PIS/Pasep',
       'Facultativo Baixa Renda - recolhimento mensal - Complemento',
       'Contribuinte Individual - Recolhimento Trimestral NIT/PIS/Pasep',
       'Contribuinte Individual - Recolhimento Trimestral - Com dedução de 45% (Lei nº 9.876/99) - NIT/PIS/Pasep',
       'Contribuinte Individual - Opção: aposentadoria apenas por idade Recolhimento Trimestral - NIT/PIS/Pasep',
       'Segurado Facultativo - recolhimento trimestral - NIT/PIS/Pasep',
       'Facultativo - Opção: aposentadoria apenas por idade - Recolhimento Trimestral - NIT/PIS/Pasep',
       'Segurado Especial - recolhimento trimestral - NIT /PIS/Pasep',
       'Facultativo Baixa Renda - recolhimento trimestral - Complemento para Plano Simplificado da Previdência Social - PSPS - Lei nº 12.470/2011',
       'Facultativo Baixa Renda - recolhimento trimestral - NIT/PIS/Pasep',
       'Facultativo Baixa Renda - recolhimento trimestral - Complemento',
       'EFD-Contribuições - Escrituração Fiscal Digital das Contribuições incidentes sobre a Receita',
       'DCTFWeb -\xa0Declaração de Débitos e Créditos Tributários Federais Previdenciários e de Outras Entidades e Fundos',
       'EFD-Reinf\xa0-\xa0Escrituração Fiscal Digital de Retenções e Outras Informações Fiscais',
       'PIS/PASEP - Retenção de contribuições – pagamentos de PJ a PJ de direito privado (Cofins, PIS/Pasep, CSLL)',
       'PIS/PASEP - Retenção – pagamentos de PJ a PJ de direito privado',
       'COFINS - Retenção de contribuições – pagamentos de PJ a PJ de direito privado (Cofins, PIS/Pasep, CSLL)',
       'COFINS - Retenção – pagamentos de PJ a PJ de direito privado',
       'CSLL - Retenção de contribuições - pagamentos de PJ a PJ de direito privado (Cofins, Pis/Pasep, CSLL)',
       'CSLL - Retenção - pagamentos de PJ a PJ de direito privado',
       'Contribuição Previdenciária sobre a Receita Bruta - Art. 7º da Lei nº 12.546/2011',
       'Contribuição Previdenciária sobre a Receita Bruta - Art. 8º da Lei nº 12.546/2011',
       'PIS/PASEP - Entidades financeiras equiparadas',
       'COFINS - Entidades financeiras equiparadas',
       'IRRF - Aluguéis e Royalties pagos a pessoa física',
       'IRRF - Rend. partes beneficiárias ou de fundador',
       'IRRF - Resgate Previdência Complementar/Modalidade Contribuição Definida/Variável - Não Optante Tributação Exclusiva',
       'IRRF - Resgate Previdência Complementar/Modalidade Benefício Definido - Não Optante Tributação Exclusiva',
       'IRRF - Resgate Previdência Complementar - Optante Tributação Exclusiva',
       'IRRF - Benefício Previdência Complementar - Não Optante Tributação Exclusiva',
       'IRRF - Benefício Previdência Complementar - Optante Tributação Exclusiva',
       'IRRF - Trabalho Assalariado (Exceto Trabalhador Doméstico)',
       'IRRF - Trabalho sem vínculo empregatício',
       'IRRF - Aposentadoria Regime Geral ou do Servidor Público',
       'IRRF - Participação nos Lucros ou Resultados - PLR',
       'IRRF - Rendimentos decorrentes de decisão da Justiça do Trabalho, exceto o disposto no art. 12-A da Lei nº 7.713, de 1988',
       'IRRF - Rendimentos Acumulados - art. 12-A da Lei nº 7.713, de 1988',
       'IRRF - Remuneração de serviços prestados por pessoa jurídica',
       'IRRF - Pagamentos de PJ a PJ por serviços de factoring',
       'IRRF - Pagamento PJ a cooperativa de trabalho',
       'IRRF - Juros e indenizações de lucros cessantes',
       'IRRF - Vida Gerador de Benefício Livre - VGBL',
       'IRRF - Indenização por danos morais',
       'IRRF - Rendimentos decorrentes de decisão da Justiça Federal, exceto o disposto no art. 12-A da Lei nº 7.713, de 1988',
       'IRRF - Rendimentos decorrentes de decisão da Justiça dos Estados/Distrito Federal, exceto o disposto no art. 12-A da Lei nº 7.713, de 1988',
       'IRRF - Demais Rendimentos',
       'IRPJ - Pagamento Unificado - Ret. Aplicável às Incorporações Imobiliárias (IRPJ, CSLL, PIS/Pasep, Cofins)',
       'IRPJ - Pagamento Unificado - Reg. Esp. Aplic. às Incorporações Imobiliárias e às Construções no âmbito do PMCMV e à Const. ou Reforma de Creches e Pré-Escolas (IRPJ, CSLL, PIS/Pasep, Cofins)',
       'IRPJ - Regime Especial de Tributação Aplicável às Incorporações Imobiliárias e às Construções',
       'CSLL - Pagamento Unificado - Ret. Aplicável às Incorporações Imobiliárias (IRPJ, CSLL, PIS/Pasep, Cofins)',
       'CSLL - Pagamento Unificado - Reg. Esp. Aplicável às Incorporações Imobiliárias e às Construções no âmbito do PMCMV e à Const. ou Reforma de Creches e Pré-Escolas (IRPJ, CSLL, PIS/Pasep, Cofins)',
       'CSLL - Regime Especial de Tributação Aplicável às Incorporações Imobiliárias e às Construções',
       'PIS/PASEP - Pagamento Unificado - Ret. Aplicável às Incorporações Imobiliárias (IRPJ, CSLL, PIS/Pasep, Cofins)',
       'PIS/PASEP - Pagamento Unificado - Reg. Esp. Aplicável às Incorporações Imobiliárias e às Construções no âmbito do PMCMV e à Const. ou Reforma de Creches e Pré-Escolas (IRPJ, CSLL, PIS/Pasep, Cofins)',
       'PIS/PASEP - Regime Especial de Tributação Aplicável às Incorporações Imobiliárias e às Construções',
       'COFINS - Pagamento Unificado - Ret. Aplicável às Incorporações Imobiliárias (IRPJ, CSLL, PIS/Pasep, Cofins)',
       'COFINS - Pagamento Unificado - Reg. Esp. Aplicável às Incorporações Imobiliárias e às Construções no âmbito do PMCMV e à Const. ou Reforma de Creches e Pré-Escolas (IRPJ, CSLL, PIS/Pasep, Cofins)',
       'COFINS - Regime Especial de Tributação Aplicável às Incorporações Imobiliárias e às Construções',
       'Pagamento Unificado - Regime de Tributação Específica do Futebol (TEF)',
       'Acordo Perante Comissão de Conciliação Prévia - Dissídio ou Acordo Coletivo e Convenção Coletiva - CEI',
       'Acordo Perante Comissão de Conciliação Prévia - Dissídio ou Acordo Coletivo e Convenção Coletiva - CEI - pagamento exclusivo para outras entidades (SESC, SESI, SENAI, etc)',
       'Acordo Perante Comissão de Conciliação Prévia - Dissídio ou Acordo Coletivo e Convenção Coletiva - CNPJ',
       'Acordo Perante Comissão de Conciliação Prévia - Dissídio ou Acordo Coletivo e Convenção Coletiva - CNPJ - pagamento exclusivo para outras entidades (SESC, SESI, SENAI, etc)',
       'Pagamento de dívida ativa parcelamento - referência (preenchimento exclusivo pelo órgão emissor)',
       'Comprev - pagamento de dívida ativa - parcelamento de regime próprio de previdência social RPPS - órgão do poder público - referência',
       'Simples Doméstico\xa0-\xa0Regime unificado de pagamento de tributos, de contribuições e dos demais encargos do empregador doméstico',
       'Simples Nacional\xa0-\xa0Regime Especial Unificado de Arrecadação de Tributos e Contribuições devidos pelas Microempresas e Empresas de Pequeno Porte.',
       'Dirbi -\xa0Declaração de Incentivos, Renúncias, Benefícios e Imunidades de Natureza Tributária',
       'PGDAS-D\xa0-\xa0Programa Gerador do Documento de Arrecadação do Simples Nacional',
       'DCTF Mensal - Declaração de Débitos e Créditos Tributários Federais – Mensal',
       'IPI - Pos.Tipi: 87.03 - Automóveis de passageiros e outros veículos automóveis principalmente concebidos para transporte de pessoas (exceto os da posição 87.02), incluídos os veículos de uso misto ("station wagons") e os automóveis de corrida',
       'IPI - Pos. Tipi: 87.06 Chassis com motor para veículos automóveis das posições 87.01 a 87.05',
       'IPI - Pos.Tipi: 84.29 - "Bulldozers", "angledozers", niveladores, raspotransportadores ("scrapers"), pás mecânicas, escavadores, carregadoras e pás carregadoras, compactadores e rolos ou cilindros compressores, autopropulsados',
       'IPI - Pos.Tipi: 84.32 - Máquinas e aparelhos de uso agrícola, hortícola ou florestal, para preparação ou trabalho do solo ou para cultura; rolos para gramados (relvados), ou para campos de esporte',
       'IPI - Pos.Tipi: 84.33 - Máquinas e aparelhos para colheita ou debulha de produtos agrícolas, incluídas as enfardadeiras de palha ou forragem; cortadores de grama (relva) e ceifeiras; máquinas para limpar ou selecionar ovos, frutas ou outros produtos agrícolas, exceto as da posição 84.37',
       'IPI - Pos.Tipi: 87.01 - Tratores (exceto os carros-tratores da posição 87.09)',
       'IPI - Pos.Tipi: 87.02 - Veículos automóveis para transporte de 10 pessoas ou mais, incluindo o motorista',
       'IPI - Pos.Tipi: 87.04 - Veículos automóveis para transporte de mercadorias',
       'IPI - Pos.Tipi: 87.05 - Veículos automóveis para usos especiais (por exemplo: auto-socorros, caminhões-guindastes, veículos de combate a incêndios, caminhões-betoneiras, veículos para varrer, veículos para espalhar, veículos-oficinas, veículos radiológicos), exceto os concebidos principalmente para transporte de pessoas ou de mercadorias',
       'IPI - Pos.Tipi:87.11 - Motocicletas (incluídos os ciclomotores) e outros ciclos equipados com motor auxiliar, mesmo com carro lateral; carros laterais',
       'IPI - Tabaco e seus Sucedâneos Manufaturados, Exceto Cigarros Contendo Tabaco (Cigarros dos cód. 2402.90.00 da Tipi)',
       'IPI - Todos os produtos, com exceção de: bebidas (Capítulo 22), Tabaco e seus Sucedâneos Manufaturados (Capítulo 24) e os das posições 84.29, 84.32, 84.33, 87.01 a 87.06 e 87.11 da Tipi',
       'IPI - Bebidas do capítulo 22 da Tipi',
       'IPI - Cervejas - Tributação de Bebidas Frias - previsto nos arts. 14 a 36 da Lei nº 13.097, de 19 de janeiro de 2015',
       'IPI - Demais bebidas - Tributação de Bebidas Frias - previsto nos arts. 14 a 36 da Lei nº 13.097, de 19 de janeiro de 2015',
       'PIS/PASEP - Faturamento', 'PIS/PASEP - Folha de Salários',
       'PIS/PASEP - Pessoa jurídica de direito público',
       'PIS/PASEP - Fabricantes/Importadores de Veículos em substituição tributária',
       'PIS/PASEP - Combustíveis', 'PIS/PASEP - Não-cumulativa',
       'PIS/PASEP - Vendas à Zona Franca de Manaus (ZFM) - Substituição Tributária',
       'PIS/PASEP - Cervejas - Tributação de Bebidas Frias - previsto nos arts. 14 a 36 da Lei nº 13.097, de 19 de janeiro de 2015',
       'PIS/PASEP - Demais bebidas - Tributação de Bebidas Frias - previsto nos arts. 14 a 36 da Lei nº 13.097, de 19 de janeiro de 2015',
       'PIS/PASEP - Álcool - Regime Especial de Apuração e Pagamento previsto no § 4º do art. 5º da Lei nº 9.718, de 27 de novembro de 1998',
       'COFINS - Demais Entidades',
       'COFINS - Fabricantes/Importadores de Veículos em substituição tributária',
       'COFINS - Combustíveis', 'COFINS - Não-cumulativa',
       'COFINS - Vendas à Zona Franca de Manaus (ZFM) - Substituição Tributária',
       'COFINS - Cervejas - Tributação de Bebidas Frias - previsto nos arts. 14 a 36 da Lei nº 13.097, de 19 de janeiro de 2015',
       'COFINS - Demais bebidas - Tributação de Bebidas Frias - previsto nos arts. 14 a 36 da Lei nº 13.097, de 19 de janeiro de 2015',
       'COFINS - Álcool - Regime Especial de Apuração e Pagamento previsto no § 4º do art. 5º da Lei nº 9.718, de 27 de novembro de 1998',
       'IRRF - Fundos de Investimento Imobiliário - Rendimentos e Ganhos de Capital Distribuídos',
       'IRRF - Rendimentos de Residentes ou Domiciliados no Exterior - Pessoa Jurídica - Ganhos de capital de alienação de bens e direitos do ativo circulante localizados no Brasil',
       'IRPF - Recolhimento mensal (Carnê-Leão)',
       'IRPF - Ganhos de capital na alienação de bens e direitos',
       'IRPF -\xa0Ganhos de Capital na Alienação de Bens e Direitos Localizados no Exterior',
       'IRPF - Ganhos líquidos em operações em bolsa',
       'IRPF -\xa0Ganhos de Capital de Depósito em Conta Corrente, Cartão de Crédito ou Débito no Exterior',
       'IOF - Imposto sobre Operações de Crédito, Câmbio e Seguro, ou Relativas a Títulos ou Valores Mobiliários - Contrato de Derivativos',
       'IRPJ - PJ obrigadas à apuração com base no lucro real - Entidades Financeiras - Balanço Trimestral\xa0(1ª quota)',
       'IRPJ - PJ obrigadas à apuração com base no lucro real - Entidades Financeiras - Estimativa Mensal',
       'IRPJ - PJ obrigadas à apuração com base no lucro real - Demais Entidades - Balanço Trimestral\xa0(1ª quota)',
       'IRPJ - PJ obrigadas à apuração com base no lucro real - Demais Entidades - Estimativa Mensal',
       'IRPJ - Optantes pela apuração com base no lucro real - Balanço Trimestral\xa0(1ª quota)',
       'IRPJ - Optantes pela apuração com base no lucro real - Estimativa Mensal',
       'IRPJ - Lucro Presumido\xa0(1ª quota)',
       'IRPJ - Lucro Arbitrado\xa0(1ª quota)',
       'IRPJ - Ganhos Líquidos em Operações na Bolsa – Lucro Real',
       'IRPJ - Ganhos Líquidos em Operações na Bolsa – Lucro Presumido ou Arbitrado',
       'IRPJ - Ganho de Capital - Alienação de Ativos de ME/EPP optantes pelo Simples Nacional',
       'CSLL - PJ que apuram o IRPJ com base no lucro real - Entidades Financeiras - Balanço Trimestral\xa0(1ª quota)',
       'CSLL - PJ que apuram o IRPJ com base no lucro real - Entidades Financeiras - Estimativa Mensal',
       'CSLL - PJ que apuram o IRPJ com base no lucro real - Demais Entidades - Balanço Trimestral (1ª quota)',
       'CSLL - PJ que apuram o IRPJ com base no lucro real - Demais Entidades - Estimativa mensal',
       'CSLL - PJ que apuram o IRPJ com base no lucro presumido ou arbitrado\xa0(1ª quota)',
       'REFIS - Parcelamento vinculado à receita bruta',
       'REFIS - Parcelamento alternativo',
       'REFIS - ITR/Exercícios até 1996',
       'REFIS - ITR/Exercícios a partir de 1997', 'PAES - Pessoa Física',
       'PAES - Microempresa', 'PAES - Empresa de Pequeno Porte',
       'PAES - Demais pessoas jurídicas', 'PAES - Paes ITR',
       'PAEX - Art. 1º MP nº 303/2006 - Pessoa jurídica optante pelo Simples',
       'PAEX - Art. 1º MP nº 303/2006 - Demais pessoas jurídicas',
       'PAEX - Art. 8º MP nº 303/2006 - Pessoa jurídica optante pelo Simples',
       'PAEX - Art. 9º MP nº 303/2006 - Pessoa jurídica optante pelo Simples',
       'Parcelamento Especial - Simples Nacional Art. 7º § 3º IN/RFB nº 767/2007 - Pessoa jurídica optante pelo Simples Nacional',
       'Parcelamento para Ingresso no Simples Nacional - 2009 Art. 7º § 3º IN/RFB nº 902/2008 - Pessoa jurídica optante pelo Simples Nacional',
       'Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º',
       'Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º',
       'Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º',
       'Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º',
       'Parcelamento Lei nº 11.941, de 2009 - PGFN - Parcelamento Dívida Decorrente de Aproveitamento Indevido de Créditos de IPI - Art. 2º',
       'Parcelamento Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º',
       'Parcelamento Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º',

In [70]:
df[df.columns[:7]].tail(10)

     data_evento           tipo codigo_darf codigo_gps                                                                        documento                                                                                                                                                          descricao periodo_fato_gerador
3311  2025-10-31      documento        None       None  DAS-MEI (Documento de Arrecadação Simplificada do Microempreendedor Individual)                                     Parcelamento - Simples Nacional Art. 7º § 3º IN/RFB nº 1.508/2014 - Microempreendedor Individual optante pelo Simples Nacional             Diversos
3312  2025-10-31      documento        None       None                               DAS (Documento de Arrecadação do Simples Nacional)                                         Parcelamento Especial - Simples Nacional Art. 5º § 3º IN/RFB nº 1.677/2016 - Pessoa jurídica optante pelo Simples Nacional             Diversos
3313  2025-10-31      documento        None       None  DAS-MEI (Documento de Arrecadação Simplificada do Microempreendedor Individual)                                     Parcelamento - Simples Nacional Art. 4º § 3º IN/RFB nº 1.713/2017 - Microempreendedor Individual optante pelo Simples Nacional             Diversos
3314  2025-10-31      documento        None       None                               DAS (Documento de Arrecadação do Simples Nacional)                               Programa Especial de Regularização Tributária das Microempresas e Empresas de Pequeno Porte optantes pelo Simples Nacional (Pert-SN)             Diversos
3315  2025-10-31      documento        None       None  DAS-MEI (Documento de Arrecadação Simplificada do Microempreendedor Individual)  Programa Especial de Regularização Tributária das Microempresas e Empresas de Pequeno Porte optantes pelo Simples Nacional (Pert-SN) Microempreendedor Individual             Diversos
3316  2025-10-31  declaracao_pj        None       None                                                                             None                                                                                                    DCTFWeb - Declaração de Débitos e Créditos Tributários Federais        Setembro/2025
3317  2025-10-31  declaracao_pj        None       None                                                                             None                                                                                                      DME - Declaração de Operações Liquidadas com Moeda em Espécie        Setembro/2025
3318  2025-10-31  declaracao_pj        None       None                                                                             None                                                                                                                      DOI - Declaração sobre Operações Imobiliárias        Setembro/2025
3319  2025-10-31  declaracao_pf        None       None                                                                             None                                                                                                      DME - Declaração de Operações Liquidadas com Moeda em Espécie        Setembro/2025
3320  2025-10-31  declaracao_pf        None       None                                                                             None                                                                                                                      DOI - Declaração sobre Operações Imobiliárias        Setembro/2025

In [71]:
import json
import pandas as pd
from datetime import datetime

# Passo 1: Carregar o JSON do seu arquivo
with open(f'../data/transformed/agenda_tributaria_{ano_selecionado}.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Lista para armazenar todos os eventos "aplanados"
eventos_com_meta = []

# Passo 2: Iterar sobre a estrutura aninhada e extrair os dados, URLs e o nome do mês
# Itera sobre os meses do JSON
for mes_nome, mes_info in data['meses'].items():
    mes_url = mes_info['url']
    
    # Itera sobre os dias dentro de cada mês
    for dia_chave, dia_info in mes_info['dias'].items():
        dia_url = dia_info['url']
        
        # Converte a chave do dia (ex: 'dia-06-01-2025') para o formato de data
        data_str = dia_chave.replace('dia-', '')
        data_evento = datetime.strptime(data_str, '%d-%m-%Y').strftime('%Y-%m-%d')
        
        # Itera sobre a lista de eventos de cada dia
        for evento in dia_info['eventos']:
            
            # Cria uma nova linha de dados (dicionário) com todas as informações
            evento_com_meta = evento.copy()
            evento_com_meta['data_evento'] = data_evento
            evento_com_meta['mes_url'] = mes_url
            evento_com_meta['dia_url'] = dia_url
            evento_com_meta['nome_mes'] = mes_nome # Adiciona o nome do mês
            
            # Adiciona a nova linha à lista de eventos
            eventos_com_meta.append(evento_com_meta)

# Passo 3: Criar um DataFrame com os dados transformados
df = pd.DataFrame(eventos_com_meta)

# Passo 4: Realizar as transformações finais no DataFrame
# Renomeia as colunas para o padrão do banco de dados
df.rename(columns={
    'descricao': 'descricao',
    'tipo': 'tipo',
    'codigo_darf': 'codigo_darf',
    'codigo_gps': 'codigo_gps',
    'documento': 'documento',
    'periodo_fato_gerador': 'periodo_fato_gerador',
    'data_evento': 'data_evento'
}, inplace=True)

# Reordena as colunas para uma melhor visualização
colunas_ordenadas = [
    'data_evento', 'nome_mes', 'tipo', 'codigo_darf', 'codigo_gps', 'documento', 'descricao', 'periodo_fato_gerador','mes_url', 'dia_url'
]
df = df[colunas_ordenadas]

# Preenche os valores ausentes (NaN) com None, o que é ideal para o SQL
df = df.where(pd.notnull(df), None)

# Exibe o DataFrame pronto para ser inserido
df

     data_evento nome_mes           tipo codigo_darf codigo_gps documento                                                        descricao   periodo_fato_gerador                                                                          mes_url                                                                                         dia_url
0     2025-01-06  janeiro           darf        8053       None      None                     IRRF - Títulos de Renda Fixa - Pessoa Física  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
1     2025-01-06  janeiro           darf        3426       None      None                   IRRF - Títulos de Renda Fixa - Pessoa Jurídica  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
2     2025-01-06  janeiro           darf        6800       None      None      IRRF - Fundo de Investimento sujeito à tributação periódica  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
3     2025-01-06  janeiro           darf        6813       None      None                            IRRF - Fundo de Investimento em Ações  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
4     2025-01-06  janeiro           darf        5273       None      None                                         IRRF - Operações de SWAP  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025
...          ...      ...            ...         ...        ...       ...                                                              ...                    ...                                                                              ...                                                                                             ...
3316  2025-10-31  outubro  declaracao_pj        None       None      None  DCTFWeb - Declaração de Débitos e Créditos Tributários Federais          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025
3317  2025-10-31  outubro  declaracao_pj        None       None      None    DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025
3318  2025-10-31  outubro  declaracao_pj        None       None      None                    DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025
3319  2025-10-31  outubro  declaracao_pf        None       None      None    DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025
3320  2025-10-31  outubro  declaracao_pf        None       None      None                    DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025

[3321 rows x 10 columns]

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3321 entries, 0 to 3320
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   data_evento           3321 non-null   object
 1   nome_mes              3321 non-null   object
 2   tipo                  3321 non-null   object
 3   codigo_darf           2707 non-null   object
 4   codigo_gps            410 non-null    object
 5   documento             80 non-null     object
 6   descricao             3321 non-null   object
 7   periodo_fato_gerador  3125 non-null   object
 8   mes_url               3321 non-null   object
 9   dia_url               3321 non-null   object
dtypes: object(10)
memory usage: 259.6+ KB

In [73]:
len(df)

3321

In [74]:
df["periodo_fato_gerador"].unique()

array(['21 a 31/dezembro/2024', '1º a 30/novembro/2024', 'Dezembro/2024',
       '1º a 31/dezembro/2024', '1º a 10/janeiro/2025',
       '16 a 31/dezembro/2024', '1º outubro a 31 dezembro/2024',
       'Novembro/2024', 'Diversos', '11 a 20/janeiro/2025',
       'Outubro a Dezembro/2024', '1º a 15/janeiro/2025',
       '---------------', '21 a 31/janeiro/2025', 'Janeiro/2025',
       '1º a 31/janeiro/2025', '1º a 10/fevereiro/2025',
       '16 a 31/janeiro/2025', '11 a 20/fevereiro/2025',
       '11 a 20/fevereiro/20255', '1º a 15/fevereiro/2025', None,
       'Ano-calendário de 2024', 'Julho a Dezembro/2024',
       '21 a 28/fevereiro/2025', 'Fevereiro/2025',
       '1º a 28/fevereiro/2025', '1º a 10/março/2025',
       '16 a 28/fevereiro/2025', '11 a 20/março/2025', 'Fevereiro/20255',
       '1º a 15/março/2025', '21 a 31/março/2025', 'Março/2025',
       '1º a 31/março/2025', '1º a 10/abril/2025', '16 a 31/março/2025',
       '1º janeiro a 31 março/2025', '11 a 20/abril/2025',
       'Janeiro a Março/2025', '1º a 15/abril/2025', '21 a 30/abril/2025',
       'Abril/2025', '1º a 30/abril/2025', '1º a 10/maio/2025',
       '16 a 30/abril/2025', '11 a 20/maio/2025', 'Ano-Calendário 2024',
       '1º a 15/maio/2025', '21 a 31/maio/2025', 'Maio/2025',
       '1º a 31/maio/2025', '1º a 10/junho/2025', '16 a 31/maio/2025',
       '11 a 20/junho/2025', '1º a 15/junho/2025', '21 a 30/junho/2025',
       'Junho/2025', '1º a 30/junho/2025', '1º a 10/julho/2025',
       '16 a 30/junho/2025', '1º abril a 30 junho/2025',
       '11 a 20/julho/2025', 'Abril a Junho/2025', '1º a 15/julho/2025',
       '21 a 31/julho/2025', 'Julho/2025', '1º a 31/julho/2025',
       '1º a 10/agosto/2025', '16 a 31/julho/2025', '11 a 20/agosto/2025',
       '1º a 15/agosto/2025', 'Janeiro a Junho/2025',
       '21 a 31/agosto/2025', 'Agosto/2025', '1º a 31/agosto/2025',
       '1º a 10/setembro/2025', '16 a 31/agosto/2025',
       '11 a 20/setembro/2025', '1º a 15/setembro/2025',
       '1º/janeiro/2025', 'Exercício - 2025', '21 a 30/setembro/2025',
       'Setembro/2025', '1º a 30/setembro/2025', '1º a 10/outubro/2025',
       '16 a 30/setembro/2025', '1º julho a 30 setembro/2025',
       '11 a 20/outubro/2025', 'Julho a Setembro/2025',
       '1º a 15/outubro/2025'], dtype=object)

In [75]:
teste = df["periodo_fato_gerador"].value_counts().to_dict()
teste

{'Diversos': 638,
 'Dezembro/2024': 112,
 'Agosto/2025': 112,
 'Abril/2025': 112,
 'Janeiro/2025': 111,
 'Junho/2025': 111,
 'Março/2025': 111,
 'Fevereiro/2025': 110,
 'Setembro/2025': 110,
 'Julho/2025': 110,
 'Maio/2025': 110,
 '1º a 10/março/2025': 35,
 '21 a 30/abril/2025': 35,
 '1º a 10/maio/2025': 35,
 '11 a 20/junho/2025': 35,
 '21 a 30/junho/2025': 35,
 '1º a 10/junho/2025': 35,
 '11 a 20/maio/2025': 35,
 '11 a 20/abril/2025': 35,
 '21 a 31/março/2025': 35,
 '11 a 20/janeiro/2025': 35,
 '21 a 31/dezembro/2024': 35,
 '21 a 31/janeiro/2025': 35,
 '1º a 10/fevereiro/2025': 35,
 '1º a 10/janeiro/2025': 35,
 '21 a 28/fevereiro/2025': 35,
 '1º a 10/julho/2025': 35,
 '1º a 10/agosto/2025': 35,
 '11 a 20/julho/2025': 35,
 '1º a 10/setembro/2025': 35,
 '1º a 10/outubro/2025': 35,
 '11 a 20/outubro/2025': 35,
 '21 a 30/setembro/2025': 35,
 '11 a 20/setembro/2025': 35,
 '21 a 31/julho/2025': 35,
 '21 a 31/maio/2025': 35,
 '21 a 31/agosto/2025': 35,
 '11 a 20/agosto/2025': 35,
 '1º a 10/abril/2025': 35,
 '11 a 20/março/2025': 35,
 '11 a 20/fevereiro/2025': 34,
 'Outubro a Dezembro/2024': 25,
 'Janeiro a Março/2025': 25,
 'Abril a Junho/2025': 25,
 '1º a 31/janeiro/2025': 23,
 'Ano-calendário de 2024': 16,
 '1º a 30/abril/2025': 13,
 '1º a 31/março/2025': 13,
 '1º a 28/fevereiro/2025': 13,
 '1º a 31/dezembro/2024': 13,
 '1º a 30/junho/2025': 11,
 '1º a 31/agosto/2025': 11,
 '1º a 30/setembro/2025': 11,
 '1º a 31/maio/2025': 11,
 '1º a 31/julho/2025': 11,
 '1º outubro a 31 dezembro/2024': 9,
 '1º janeiro a 31 março/2025': 9,
 '1º julho a 30 setembro/2025': 9,
 '1º abril a 30 junho/2025': 9,
 'Julho a Setembro/2025': 8,
 'Ano-Calendário 2024': 7,
 'Novembro/2024': 3,
 'Janeiro a Junho/2025': 3,
 '1º a 15/janeiro/2025': 2,
 '1º a 30/novembro/2024': 2,
 '16 a 31/dezembro/2024': 2,
 '1º a 15/agosto/2025': 2,
 'Julho a Dezembro/2024': 2,
 '1º a 15/fevereiro/2025': 2,
 '16 a 31/janeiro/2025': 2,
 '---------------': 2,
 '16 a 28/fevereiro/2025': 2,
 '1º a 15/abril/2025': 2,
 '1º a 15/maio/2025': 2,
 '16 a 30/setembro/2025': 2,
 '1º a 15/junho/2025': 2,
 '16 a 30/abril/2025': 2,
 '16 a 31/maio/2025': 2,
 '16 a 31/março/2025': 2,
 '1º a 15/março/2025': 2,
 '16 a 30/junho/2025': 2,
 '1º a 15/julho/2025': 2,
 '1º a 15/outubro/2025': 2,
 '16 a 31/julho/2025': 2,
 '1º a 15/setembro/2025': 2,
 '16 a 31/agosto/2025': 2,
 '1º/janeiro/2025': 2,
 '11 a 20/fevereiro/20255': 1,
 'Fevereiro/20255': 1,
 'Exercício - 2025': 1}

In [76]:
import pandas as pd
import re
from calendar import monthrange
from datetime import datetime

# 1. Dicionário de Mapeamento de Meses (em minúsculas)
meses_map = {
    'janeiro': '01', 'fevereiro': '02', 'março': '03', 'abril': '04',
    'maio': '05', 'junho': '06', 'julho': '07', 'agosto': '08',
    'setembro': '09', 'outubro': '10', 'novembro': '11', 'dezembro': '12'
}

# ----------------------------------------------------------------------
# FUNÇÕES AUXILIARES DE PRÉ-PROCESSAMENTO
# ----------------------------------------------------------------------

def _preparar_periodo(periodo):
    """Limpa e normaliza o período, retornando a string e o valor numérico."""
    periodo_limpo = str(periodo).lower().strip().replace('º', '')
    
    # 2.1. Tratamento de valores inválidos que devem ser ignorados
    if periodo_limpo in ['diversos', '---------------', 'none', 'n/a']:
        return None, None
    
    # Prepara o período numérico (substitui nomes de meses por números)
    periodo_numerico = periodo_limpo
    for pt, num in meses_map.items():
        # Usa word boundary (\b) para evitar substituições parciais
        periodo_numerico = re.sub(r'\b' + pt + r'\b', num, periodo_numerico)
        
    return periodo_limpo, periodo_numerico

# ----------------------------------------------------------------------
# FUNÇÕES AUXILIARES DE TRATAMENTO DE PADRÕES
# ----------------------------------------------------------------------

def _tratar_ano_calendario(periodo_original):
    """2.2. Tratamento de Ano-calendário (Ex: 'Ano-calendário de 2024')"""
    match_ano = re.search(r'202\d', periodo_original)
    if match_ano and ('ano-calendário' in periodo_original or 'exercício' in periodo_original):
        ano = int(match_ano.group(0))
        return pd.to_datetime(f'01/01/{ano}', format='%d/%m/%Y'), pd.to_datetime(f'31/12/{ano}', format='%d/%m/%Y')
    return pd.NaT, pd.NaT

def _tratar_mes_ano_simples(periodo_numerico):
    """2.3. Mês/Ano Simples (Ex: 05/2025 ou 02/20255 - com a correção)"""
    # Permite de 4 a 5 dígitos no ano para lidar com erros de digitação (ex: 20255)
    match_mes_ano = re.search(r'(\d{2})/?(\d{4,5})$', periodo_numerico) 
    if match_mes_ano:
        mes = int(match_mes_ano.group(1))
        
        # Corrige o ano, pegando apenas os 4 primeiros dígitos
        ano_str = match_mes_ano.group(2)
        ano = int(ano_str[:4]) 
        
        data_inicio = pd.to_datetime(f'01/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
        
        try:
            # Obtém o último dia do mês com precisão
            dias_no_mes = monthrange(ano, mes)[1] 
            data_fim = pd.to_datetime(f'{dias_no_mes}/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
            return data_inicio, data_fim
        except ValueError:
            return pd.NaT, pd.NaT # Inválido se o mês ou ano for maluco
    return pd.NaT, pd.NaT

def _tratar_intervalo_mes_a_mes(periodo_numerico):
    """2.4. Intervalo de Mês a Mês/Ano (Ex: 10 a 12/2024)"""
    match_intervalo_meses_simples = re.search(r'(\d{2})\s?a\s?(\d{2})/(\d{4})', periodo_numerico)
    if match_intervalo_meses_simples:
        mes_inicio_num, mes_fim_num, ano = match_intervalo_meses_simples.groups()
        
        ano_int = int(ano)
        mes_fim_int = int(mes_fim_num)
        
        data_inicio = pd.to_datetime(f'01/{mes_inicio_num}/{ano}', format='%d/%m/%Y', errors='coerce')
        
        try:
            dias_no_mes_fim = monthrange(ano_int, mes_fim_int)[1]
            data_fim = pd.to_datetime(f'{dias_no_mes_fim}/{mes_fim_num}/{ano}', format='%d/%m/%Y', errors='coerce')
            return data_inicio, data_fim
        except ValueError:
            return pd.NaT, pd.NaT
    return pd.NaT, pd.NaT

def _tratar_intervalo_completo(periodo_numerico):
    """2.5. Intervalo de Data Completa (Ex: 1/10 a 31/12/2024)"""
    # Padrão: dia/mês a dia/mês/ano (usando os números dos meses)
    match_intervalo_completo = re.search(r'(\d{1,2})\s?(\d{2})\s?a\s?(\d{1,2})\s?(\d{2})/(\d{4})', periodo_numerico)
    if match_intervalo_completo:
        dia_inicio, mes_inicio, dia_fim, mes_fim, ano = match_intervalo_completo.groups()
        
        data_inicio = pd.to_datetime(f'{dia_inicio}/{mes_inicio}/{ano}', format='%d/%m/%Y', errors='coerce')
        data_fim = pd.to_datetime(f'{dia_fim}/{mes_fim}/{ano}', format='%d/%m/%Y', errors='coerce')
        return data_inicio, data_fim
    return pd.NaT, pd.NaT

def _tratar_intervalo_dias_mesmo_mes(periodo_numerico):
    """2.6. Intervalo de Dias em um Único Mês (Ex: 1 a 10/03/2025)"""
    match_intervalo_dias = re.search(r'(\d{1,2})\s?a\s?(\d{1,2})/(\d{2})/(\d{4})', periodo_numerico)
    if match_intervalo_dias:
        dia_inicio, dia_fim, mes, ano = match_intervalo_dias.groups()
        data_inicio = pd.to_datetime(f'{dia_inicio}/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
        data_fim = pd.to_datetime(f'{dia_fim}/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
        return data_inicio, data_fim
    return pd.NaT, pd.NaT

def _tratar_intervalo_dias_mes_extenso(periodo_limpo):
    """2.7. Intervalo de Dias com Mês por Extenso (Ex: 21 a 31/dezembro/2024)"""    
    match = re.search(r'(\d{1,2})\s?a\s?(\d{1,2})/([a-zç]+)/(\d{4})', periodo_limpo)
    if match:
        dia_inicio, dia_fim, mes_extenso, ano = match.groups()
        mes = meses_map.get(mes_extenso)
        if mes:
            data_inicio = pd.to_datetime(f'{dia_inicio}/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
            data_fim = pd.to_datetime(f'{dia_fim}/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
            return data_inicio, data_fim
    return pd.NaT, pd.NaT


# ----------------------------------------------------------------------
# FUNÇÃO MESTRE ORQUESTRADORA
# ----------------------------------------------------------------------

def padronizar_periodo(periodo):
    """
    Função principal que tenta padronizar o periodo_fato_gerador em 
    data_inicio e data_fim, usando funções auxiliares.
    """
    if pd.isna(periodo):
        return pd.NaT, pd.NaT
        
    # Passo 1: Limpeza e Checagem de Invalidade
    periodo_limpo, periodo_numerico = _preparar_periodo(periodo)
    
    if periodo_limpo is None: # Se foi tratado como 'Diversos', '---------------', etc.
        return pd.NaT, pd.NaT

    # Passo 2: Orquestração. Tenta em ordem de complexidade
    
    # Tenta o Intervalo de Dias com Mês por Extenso (Ex: 21 a 31/dezembro/2024)    
    data_inicio, data_fim = _tratar_intervalo_dias_mes_extenso(periodo_limpo)
    if data_inicio is not pd.NaT:
        return data_inicio, data_fim

    # Tenta o Intervalo de Dias em um Único Mês (Ex: 1 a 10/03/2025)
    data_inicio, data_fim = _tratar_intervalo_dias_mesmo_mes(periodo_numerico)
    if data_inicio is not pd.NaT:
        return data_inicio, data_fim
    
    # Tenta o Intervalo de Mês a Mês (Ex: Outubro a Dezembro/2024)
    data_inicio, data_fim = _tratar_intervalo_mes_a_mes(periodo_numerico)
    if data_inicio is not pd.NaT:
        return data_inicio, data_fim


    # Tenta o Intervalo de Data Completa (Ex: 1 Outubro a 31 Dezembro/2024)
    data_inicio, data_fim = _tratar_intervalo_completo(periodo_numerico)
    if data_inicio is not pd.NaT:
        return data_inicio, data_fim

    # Tenta o Mês/Ano Simples (Ex: Maio/2025) - Mais comum e inclui a correção de dígitos
    data_inicio, data_fim = _tratar_mes_ano_simples(periodo_numerico)
    if data_inicio is not pd.NaT:
        return data_inicio, data_fim
        
    # Tenta o Ano-Calendário (Ex: Ano-calendário de 2024) - Mantido por último pela sua especificidade textual
    data_inicio, data_fim = _tratar_ano_calendario(periodo_limpo)
    if data_inicio is not pd.NaT:
        return data_inicio, data_fim

    # Passo 3: Não Padronizado
    return pd.NaT, pd.NaT

# ----------------------------------------------------------------------
# EXEMPLO DE APLICAÇÃO
# ----------------------------------------------------------------------

df[['data_inicio', 'data_fim']] = df['periodo_fato_gerador'].apply(
     lambda x: pd.Series(padronizar_periodo(x))
)

In [77]:
# import pandas as pd
# import re
# from calendar import monthrange
# from datetime import datetime
# from IPython.display import display
# import json

# # 1. Dicionário de Mapeamento de Meses (em minúsculas)
# meses_map = {
#     'janeiro': '01', 'fevereiro': '02', 'março': '03', 'abril': '04',
#     'maio': '05', 'junho': '06', 'julho': '07', 'agosto': '08',
#     'setembro': '09', 'outubro': '10', 'novembro': '11', 'dezembro': '12'
# }

# def padronizar_periodo(periodo):
#     # Trata None/NaN primeiro
#     if pd.isna(periodo):
#         return pd.NaT, pd.NaT

#     periodo = str(periodo).lower().strip().replace('º', '') 
    
#     # 2.1. Tratamento de valores inválidos
#     if periodo in ['diversos', '---------------', 'none', 'n/a']:
#         return pd.NaT, pd.NaT
        
#     # Prepara o período: substitui **apenas** nomes de meses por números
#     periodo_numerico = periodo
#     for pt, num in meses_map.items():
#         # Usa word boundary (\b) para garantir que apenas o nome do mês seja substituído
#         periodo_numerico = re.sub(r'\b' + pt + r'\b', num, periodo_numerico)

#     # 2.2. Tratamento de Ano-calendário (Ex: 'Ano-calendário de 2024')
#     match_ano = re.search(r'202\d', periodo)
#     if match_ano and ('ano-calendário' in periodo or 'exercício' in periodo):
#         ano = int(match_ano.group(0))
#         return pd.to_datetime(f'01/01/{ano}', format='%d/%m/%Y'), pd.to_datetime(f'31/12/{ano}', format='%d/%m/%Y')

#     # --- TRATAMENTO CORRIGIDO: 2.3. Mês/Ano Simples (Ex: Maio/2025 -> 01/05/2025 a 31/05/2025) ---
#     # Tenta extrair Mês/Ano (agora com números). 
#     # A verificação 'a' not in periodo foi removida pois o 'a' estava em 'janeiro', bloqueando a regra.
#     match_mes_ano = re.search(r'(\d{2})/?(\d{4})$', periodo_numerico) 
#     if match_mes_ano: # <-- Condição simplificada!
#         mes = int(match_mes_ano.group(1))
#         ano = int(match_mes_ano.group(2))
        
#         data_inicio = pd.to_datetime(f'01/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
        
#         try:
#             dias_no_mes = monthrange(ano, mes)[1] 
#             data_fim = pd.to_datetime(f'{dias_no_mes}/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
#             return data_inicio, data_fim
#         except ValueError:
#             return pd.NaT, pd.NaT

#     # 2.4. Intervalo de Mês a Mês/Ano (Ex: Outubro a Dezembro/2024 -> 01/10/2024 a 31/12/2024)
#     # Busca por: Mês1 a Mês2/Ano (usando os números dos meses, que foram substituídos)
#     match_intervalo_meses_simples = re.search(r'(\d{2})\s?a\s?(\d{2})/(\d{4})', periodo_numerico)
#     if match_intervalo_meses_simples:
#         # ... (Restante da lógica 2.4)
#         mes_inicio_num, mes_fim_num, ano = match_intervalo_meses_simples.groups()
        
#         ano_int = int(ano)
#         mes_fim_int = int(mes_fim_num)
        
#         data_inicio = pd.to_datetime(f'01/{mes_inicio_num}/{ano}', format='%d/%m/%Y', errors='coerce')
        
#         try:
#             dias_no_mes_fim = monthrange(ano_int, mes_fim_int)[1]
#             data_fim = pd.to_datetime(f'{dias_no_mes_fim}/{mes_fim_num}/{ano}', format='%d/%m/%Y', errors='coerce')
#             return data_inicio, data_fim
#         except ValueError:
#             return pd.NaT, pd.NaT

#     # 2.5. Intervalo de Data Completa (Ex: 1 outubro a 31 dezembro/2024)
#     # Padrão: dia/mês a dia/mês/ano (usando os números dos meses)
#     match_intervalo_completo = re.search(r'(\d{1,2})\s?(\d{2})\s?a\s?(\d{1,2})\s?(\d{2})/(\d{4})', periodo_numerico)
#     if match_intervalo_completo:
#         # ... (Restante da lógica 2.5)
#         dia_inicio, mes_inicio, dia_fim, mes_fim, ano = match_intervalo_completo.groups()
        
#         data_inicio = pd.to_datetime(f'{dia_inicio}/{mes_inicio}/{ano}', format='%d/%m/%Y', errors='coerce')
#         data_fim = pd.to_datetime(f'{dia_fim}/{mes_fim}/{ano}', format='%d/%m/%Y', errors='coerce')
#         return data_inicio, data_fim
    
#     # 2.6. Intervalo de Dias em um Único Mês (Ex: 1 a 10/03/2025)
#     match_intervalo_dias = re.search(r'(\d{1,2})\s?a\s?(\d{1,2})/(\d{2})/(\d{4})', periodo_numerico)
#     if match_intervalo_dias:
#         # ... (Restante da lógica 2.6)
#         dia_inicio, dia_fim, mes, ano = match_intervalo_dias.groups()
#         data_inicio = pd.to_datetime(f'{dia_inicio}/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
#         data_fim = pd.to_datetime(f'{dia_fim}/{mes}/{ano}', format='%d/%m/%Y', errors='coerce')
#         return data_inicio, data_fim
        
#     # Caso não consiga padronizar
#     return pd.NaT, pd.NaT

# # -----------------------------------------------------------
# # CÓDIGO DE APLICAÇÃO (Para você rodar):
# # -----------------------------------------------------------
# # Assume que a variável 'df' foi carregada corretamente
# # com base no seu código fornecido.

# # APLICAÇÃO:
# df[['data_inicio', 'data_fim']] = df['periodo_fato_gerador'].apply(
#      lambda x: pd.Series(padronizar_periodo(x))
# )

# # Exibe a lista de casos que AINDA NÃO foram padronizados
# print("Casos de 'periodo_fato_gerador' que não foram padronizados (espera-se apenas 'Diversos' e '---------------'):")
# nao_padronizados = df.loc[
#     df['data_inicio'].isnull() & 
#     df['data_fim'].isnull() & 
#     df['periodo_fato_gerador'].notnull(), 
#     'periodo_fato_gerador'
# ].unique().tolist()

# # Remove None/NaN se houver
# nao_padronizados_limpos = [x for x in nao_padronizados if x is not None and str(x).lower().strip() not in ['none', 'nan']]
# print(f'estou printando aqui: {nao_padronizados_limpos}')

In [78]:
df

     data_evento nome_mes           tipo codigo_darf codigo_gps documento                                                        descricao   periodo_fato_gerador                                                                          mes_url                                                                                         dia_url data_inicio   data_fim
0     2025-01-06  janeiro           darf        8053       None      None                     IRRF - Títulos de Renda Fixa - Pessoa Física  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21 2024-12-31
1     2025-01-06  janeiro           darf        3426       None      None                   IRRF - Títulos de Renda Fixa - Pessoa Jurídica  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21 2024-12-31
2     2025-01-06  janeiro           darf        6800       None      None      IRRF - Fundo de Investimento sujeito à tributação periódica  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21 2024-12-31
3     2025-01-06  janeiro           darf        6813       None      None                            IRRF - Fundo de Investimento em Ações  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21 2024-12-31
4     2025-01-06  janeiro           darf        5273       None      None                                         IRRF - Operações de SWAP  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21 2024-12-31
...          ...      ...            ...         ...        ...       ...                                                              ...                    ...                                                                              ...                                                                                             ...         ...        ...
3316  2025-10-31  outubro  declaracao_pj        None       None      None  DCTFWeb - Declaração de Débitos e Créditos Tributários Federais          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3317  2025-10-31  outubro  declaracao_pj        None       None      None    DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3318  2025-10-31  outubro  declaracao_pj        None       None      None                    DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3319  2025-10-31  outubro  declaracao_pf        None       None      None    DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3320  2025-10-31  outubro  declaracao_pf        None       None      None                    DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30

[3321 rows x 12 columns]

In [79]:
df[df['codigo_darf'] == 'Fevereiro/20255']

Empty DataFrame
Columns: [data_evento, nome_mes, tipo, codigo_darf, codigo_gps, documento, descricao, periodo_fato_gerador, mes_url, dia_url, data_inicio, data_fim]
Index: []

In [80]:
df[["data_inicio", "data_fim", "periodo_fato_gerador"]].value_counts().to_dict()

{(Timestamp('2024-12-01 00:00:00'),
  Timestamp('2024-12-31 00:00:00'),
  'Dezembro/2024'): 112,
 (Timestamp('2025-04-01 00:00:00'),
  Timestamp('2025-04-30 00:00:00'),
  'Abril/2025'): 112,
 (Timestamp('2025-08-01 00:00:00'),
  Timestamp('2025-08-31 00:00:00'),
  'Agosto/2025'): 112,
 (Timestamp('2025-01-01 00:00:00'),
  Timestamp('2025-01-31 00:00:00'),
  'Janeiro/2025'): 111,
 (Timestamp('2025-03-01 00:00:00'),
  Timestamp('2025-03-31 00:00:00'),
  'Março/2025'): 111,
 (Timestamp('2025-06-01 00:00:00'),
  Timestamp('2025-06-30 00:00:00'),
  'Junho/2025'): 111,
 (Timestamp('2025-09-01 00:00:00'),
  Timestamp('2025-09-30 00:00:00'),
  'Setembro/2025'): 110,
 (Timestamp('2025-07-01 00:00:00'),
  Timestamp('2025-07-31 00:00:00'),
  'Julho/2025'): 110,
 (Timestamp('2025-02-01 00:00:00'),
  Timestamp('2025-02-28 00:00:00'),
  'Fevereiro/2025'): 110,
 (Timestamp('2025-05-01 00:00:00'),
  Timestamp('2025-05-31 00:00:00'),
  'Maio/2025'): 110,
 (Timestamp('2025-03-21 00:00:00'),
  Timestamp('2025-03-31 00:00:00'),
  '21 a 31/março/2025'): 35,
 (Timestamp('2025-03-11 00:00:00'),
  Timestamp('2025-03-20 00:00:00'),
  '11 a 20/março/2025'): 35,
 (Timestamp('2025-05-11 00:00:00'),
  Timestamp('2025-05-20 00:00:00'),
  '11 a 20/maio/2025'): 35,
 (Timestamp('2025-05-21 00:00:00'),
  Timestamp('2025-05-31 00:00:00'),
  '21 a 31/maio/2025'): 35,
 (Timestamp('2025-05-01 00:00:00'),
  Timestamp('2025-05-10 00:00:00'),
  '1º a 10/maio/2025'): 35,
 (Timestamp('2025-06-01 00:00:00'),
  Timestamp('2025-06-10 00:00:00'),
  '1º a 10/junho/2025'): 35,
 (Timestamp('2025-02-21 00:00:00'),
  Timestamp('2025-02-28 00:00:00'),
  '21 a 28/fevereiro/2025'): 35,
 (Timestamp('2025-03-01 00:00:00'),
  Timestamp('2025-03-10 00:00:00'),
  '1º a 10/março/2025'): 35,
 (Timestamp('2024-12-21 00:00:00'),
  Timestamp('2024-12-31 00:00:00'),
  '21 a 31/dezembro/2024'): 35,
 (Timestamp('2025-01-21 00:00:00'),
  Timestamp('2025-01-31 00:00:00'),
  '21 a 31/janeiro/2025'): 35,
 (Timestamp('2025-01-11 00:00:00'),
  Timestamp('2025-01-20 00:00:00'),
  '11 a 20/janeiro/2025'): 35,
 (Timestamp('2025-01-01 00:00:00'),
  Timestamp('2025-01-10 00:00:00'),
  '1º a 10/janeiro/2025'): 35,
 (Timestamp('2025-02-01 00:00:00'),
  Timestamp('2025-02-10 00:00:00'),
  '1º a 10/fevereiro/2025'): 35,
 (Timestamp('2025-06-21 00:00:00'),
  Timestamp('2025-06-30 00:00:00'),
  '21 a 30/junho/2025'): 35,
 (Timestamp('2025-06-11 00:00:00'),
  Timestamp('2025-06-20 00:00:00'),
  '11 a 20/junho/2025'): 35,
 (Timestamp('2025-08-01 00:00:00'),
  Timestamp('2025-08-10 00:00:00'),
  '1º a 10/agosto/2025'): 35,
 (Timestamp('2025-09-01 00:00:00'),
  Timestamp('2025-09-10 00:00:00'),
  '1º a 10/setembro/2025'): 35,
 (Timestamp('2025-08-11 00:00:00'),
  Timestamp('2025-08-20 00:00:00'),
  '11 a 20/agosto/2025'): 35,
 (Timestamp('2025-09-21 00:00:00'),
  Timestamp('2025-09-30 00:00:00'),
  '21 a 30/setembro/2025'): 35,
 (Timestamp('2025-10-01 00:00:00'),
  Timestamp('2025-10-10 00:00:00'),
  '1º a 10/outubro/2025'): 35,
 (Timestamp('2025-09-11 00:00:00'),
  Timestamp('2025-09-20 00:00:00'),
  '11 a 20/setembro/2025'): 35,
 (Timestamp('2025-08-21 00:00:00'),
  Timestamp('2025-08-31 00:00:00'),
  '21 a 31/agosto/2025'): 35,
 (Timestamp('2025-04-11 00:00:00'),
  Timestamp('2025-04-20 00:00:00'),
  '11 a 20/abril/2025'): 35,
 (Timestamp('2025-07-01 00:00:00'),
  Timestamp('2025-07-10 00:00:00'),
  '1º a 10/julho/2025'): 35,
 (Timestamp('2025-07-21 00:00:00'),
  Timestamp('2025-07-31 00:00:00'),
  '21 a 31/julho/2025'): 35,
 (Timestamp('2025-07-11 00:00:00'),
  Timestamp('2025-07-20 00:00:00'),
  '11 a 20/julho/2025'): 35,
 (Timestamp('2025-04-01 00:00:00'),
  Timestamp('2025-04-10 00:00:00'),
  '1º a 10/abril/2025'): 35,
 (Timestamp('2025-04-21 00:00:00'),
  Timestamp('2025-04-30 00:00:00'),
  '21 a 30/abril/2025'): 35,
 (Timestamp('2025-10-11 00:00:00'),
  Timestamp('2025-10-20 00:00:00'),
  '11 a 20/outubro/2025'): 35,
 (Timestamp('2025-02-11 00:00:00'),
  Timestamp('2025-02-20 00:00:00'),
  '11 a 20/fevereiro/2025'): 34,
 (Timestamp('2024-10-01 00:00:00'),
  Timestamp('2024-12-31 00:00:00'),
  'Outubro a Dezembro/2024'): 25,
 (Timestamp('2025-04-01 00:00:00'),
  Timestamp('2025-06-30 00:00:00'),
  'Abril a Junho/2025'): 25,
 (Timestamp('2025-01-01 00:00:00'),
  Timestamp('2025-03-31 00:00:00'),
  'Janeiro a Março/2025'): 25,
 (Timestamp('2025-01-01 00:00:00'),
  Timestamp('2025-01-31 00:00:00'),
  '1º a 31/janeiro/2025'): 23,
 (Timestamp('2024-01-01 00:00:00'),
  Timestamp('2024-12-31 00:00:00'),
  'Ano-calendário de 2024'): 16,
 (Timestamp('2025-02-01 00:00:00'),
  Timestamp('2025-02-28 00:00:00'),
  '1º a 28/fevereiro/2025'): 13,
 (Timestamp('2025-04-01 00:00:00'),
  Timestamp('2025-04-30 00:00:00'),
  '1º a 30/abril/2025'): 13,
 (Timestamp('2025-03-01 00:00:00'),
  Timestamp('2025-03-31 00:00:00'),
  '1º a 31/março/2025'): 13,
 (Timestamp('2024-12-01 00:00:00'),
  Timestamp('2024-12-31 00:00:00'),
  '1º a 31/dezembro/2024'): 13,
 (Timestamp('2025-05-01 00:00:00'),
  Timestamp('2025-05-31 00:00:00'),
  '1º a 31/maio/2025'): 11,
 (Timestamp('2025-08-01 00:00:00'),
  Timestamp('2025-08-31 00:00:00'),
  '1º a 31/agosto/2025'): 11,
 (Timestamp('2025-07-01 00:00:00'),
  Timestamp('2025-07-31 00:00:00'),
  '1º a 31/julho/2025'): 11,
 (Timestamp('2025-06-01 00:00:00'),
  Timestamp('2025-06-30 00:00:00'),
  '1º a 30/junho/2025'): 11,
 (Timestamp('2025-09-01 00:00:00'),
  Timestamp('2025-09-30 00:00:00'),
  '1º a 30/setembro/2025'): 11,
 (Timestamp('2025-01-01 00:00:00'),
  Timestamp('2025-03-31 00:00:00'),
  '1º janeiro a 31 março/2025'): 9,
 (Timestamp('2024-10-01 00:00:00'),
  Timestamp('2024-12-31 00:00:00'),
  '1º outubro a 31 dezembro/2024'): 9,
 (Timestamp('2025-04-01 00:00:00'),
  Timestamp('2025-06-30 00:00:00'),
  '1º abril a 30 junho/2025'): 9,
 (Timestamp('2025-07-01 00:00:00'),
  Timestamp('2025-09-30 00:00:00'),
  '1º julho a 30 setembro/2025'): 9,
 (Timestamp('2025-07-01 00:00:00'),
  Timestamp('2025-09-30 00:00:00'),
  'Julho a Setembro/2025'): 8,
 (Timestamp('2024-01-01 00:00:00'),
  Timestamp('2024-12-31 00:00:00'),
  'Ano-Calendário 2024'): 7,
 (Timestamp('2024-11-01 00:00:00'),
  Timestamp('2024-11-30 00:00:00'),
  'Novembro/2024'): 3,
 (Timestamp('2025-01-01 00:00:00'),
  Timestamp('2025-06-30 00:00:00'),
  'Janeiro a Junho/2025'): 3,
 (Timestamp('2024-07-01 00:00:00'),
  Timestamp('2024-12-31 00:00:00'),
  'Julho a Dezembro/2024'): 2,
 (Timestamp('2024-11-01 00:00:00'),
  Timestamp('2024-11-30 00:00:00'),
  '1º a 30/novembro/2024'): 2,
 (Timestamp('2025-07-16 00:00:00'),
  Timestamp('2025-07-31 00:00:00'),
  '16 a 31/julho/2025'): 2,
 (Timestamp('2025-01-16 00:00:00'),
  Timestamp('2025-01-31 00:00:00'),
  '16 a 31/janeiro/2025'): 2,
 (Timestamp('2025-01-01 00:00:00'),
  Timestamp('2025-01-15 00:00:00'),
  '1º a 15/janeiro/2025'): 2,
 (Timestamp('2025-01-01 00:00:00'),
  Timestamp('2025-01-31 00:00:00'),
  '1º/janeiro/2025'): 2,
 (Timestamp('2024-12-16 00:00:00'),
  Timestamp('2024-12-31 00:00:00'),
  '16 a 31/dezembro/2024'): 2,
 (Timestamp('2025-02-16 00:00:00'),
  Timestamp('2025-02-28 00:00:00'),
  '16 a 28/fevereiro/2025'): 2,
 (Timestamp('2025-02-01 00:00:00'),
  Timestamp('2025-02-15 00:00:00'),
  '1º a 15/fevereiro/2025'): 2,
 (Timestamp('2025-04-16 00:00:00'),
  Timestamp('2025-04-30 00:00:00'),
  '16 a 30/abril/2025'): 2,
 (Timestamp('2025-09-01 00:00:00'),
  Timestamp('2025-09-15 00:00:00'),
  '1º a 15/setembro/2025'): 2,
 (Timestamp('2025-06-01 00:00:00'),
  Timestamp('2025-06-15 00:00:00'),
  '1º a 15/junho/2025'): 2,
 (Timestamp('2025-05-16 00:00:00'),
  Timestamp('2025-05-31 00:00:00'),
  '16 a 31/maio/2025'): 2,
 (Timestamp('2025-05-01 00:00:00'),
  Timestamp('2025-05-15 00:00:00'),
  '1º a 15/maio/2025'): 2,
 (Timestamp('2025-03-01 00:00:00'),
  Timestamp('2025-03-15 00:00:00'),
  '1º a 15/março/2025'): 2,
 (Timestamp('2025-03-16 00:00:00'),
  Timestamp('2025-03-31 00:00:00'),
  '16 a 31/março/2025'): 2,
 (Timestamp('2025-04-01 00:00:00'),
  Timestamp('2025-04-15 00:00:00'),
  '1º a 15/abril/2025'): 2,
 (Timestamp('2025-07-01 00:00:00'),
  Timestamp('2025-07-15 00:00:00'),
  '1º a 15/julho/2025'): 2,
 (Timestamp('2025-09-16 00:00:00'),
  Timestamp('2025-09-30 00:00:00'),
  '16 a 30/setembro/2025'): 2,
 (Timestamp('2025-08-16 00:00:00'),
  Timestamp('2025-08-31 00:00:00'),
  '16 a 31/agosto/2025'): 2,
 (Timestamp('2025-06-16 00:00:00'),
  Timestamp('2025-06-30 00:00:00'),
  '16 a 30/junho/2025'): 2,
 (Timestamp('2025-08-01 00:00:00'),
  Timestamp('2025-08-15 00:00:00'),
  '1º a 15/agosto/2025'): 2,
 (Timestamp('2025-10-01 00:00:00'),
  Timestamp('2025-10-15 00:00:00'),
  '1º a 15/outubro/2025'): 2,
 (Timestamp('2025-01-01 00:00:00'),
  Timestamp('2025-12-31 00:00:00'),
  'Exercício - 2025'): 1,
 (Timestamp('2025-02-11 00:00:00'),
  Timestamp('2025-02-20 00:00:00'),
  '11 a 20/fevereiro/20255'): 1,
 (Timestamp('2025-02-01 00:00:00'),
  Timestamp('2025-02-28 00:00:00'),
  'Fevereiro/20255'): 1}

In [81]:
print(len(df[["data_inicio"]]))
print(df[["data_inicio"]].count())
print(len(df[["data_fim"]]))
print(df[["data_fim"]].count())
print(len(df[["periodo_fato_gerador"]]))
print(df[["periodo_fato_gerador"]].count())
print(df[['data_inicio', 'data_fim']].isnull().sum())

3321
data_inicio    2485
dtype: int64
3321
data_fim    2485
dtype: int64
3321
periodo_fato_gerador    3125
dtype: int64
data_inicio    836
data_fim       836
dtype: int64

In [82]:
df[df['data_inicio'].isnull() | df['data_fim'].isnull() | df['periodo_fato_gerador'].isnull()]

     data_evento nome_mes       tipo codigo_darf codigo_gps                                                                        documento                                                                                                                                                                     descricao periodo_fato_gerador                                                                          mes_url                                                                                         dia_url data_inicio data_fim
148   2025-01-20  janeiro        gps        None       2852                                                                             None                                                                        Acordo Perante Comissão de Conciliação Prévia - Dissídio ou Acordo Coletivo e Convenção Coletiva - CEI             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-20-01-2025         NaT      NaT
149   2025-01-20  janeiro        gps        None       2879                                                                             None   Acordo Perante Comissão de Conciliação Prévia - Dissídio ou Acordo Coletivo e Convenção Coletiva - CEI - pagamento exclusivo para outras entidades (SESC, SESI, SENAI, etc)             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-20-01-2025         NaT      NaT
150   2025-01-20  janeiro        gps        None       2950                                                                             None                                                                       Acordo Perante Comissão de Conciliação Prévia - Dissídio ou Acordo Coletivo e Convenção Coletiva - CNPJ             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-20-01-2025         NaT      NaT
151   2025-01-20  janeiro        gps        None       2976                                                                             None  Acordo Perante Comissão de Conciliação Prévia - Dissídio ou Acordo Coletivo e Convenção Coletiva - CNPJ - pagamento exclusivo para outras entidades (SESC, SESI, SENAI, etc)             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-20-01-2025         NaT      NaT
152   2025-01-20  janeiro        gps        None       6106                                                                             None                                                                              Pagamento de dívida ativa parcelamento - referência (preenchimento exclusivo pelo órgão emissor)             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-20-01-2025         NaT      NaT
...          ...      ...        ...         ...        ...                                                                              ...                                                                                                                                                                           ...                  ...                                                                              ...                                                                                             ...         ...      ...
3311  2025-10-31  outubro  documento        None       None  DAS-MEI (Documento de Arrecadação Simplificada do Microempreendedor Individual)                                                Parcelamento - Simples Nacional Art. 7º § 3º IN/RFB nº 1.508/2014 - Microempreendedor Individual optante pelo Simples Nacional             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT
3312  2025-10-31  outubro  documento        None       None                               DAS (Documento de Arrecadação do Simples Nacional)                                                    Parcelamento Especial - Simples Nacional Art. 5º § 3º IN/RFB nº 1.677/2016 - Pessoa jurídica optante pelo Simples Nacional             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT
3313  2025-10-31  outubro  documento        None       None  DAS-MEI (Documento de Arrecadação Simplificada do Microempreendedor Individual)                                                Parcelamento - Simples Nacional Art. 4º § 3º IN/RFB nº 1.713/2017 - Microempreendedor Individual optante pelo Simples Nacional             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT
3314  2025-10-31  outubro  documento        None       None                               DAS (Documento de Arrecadação do Simples Nacional)                                          Programa Especial de Regularização Tributária das Microempresas e Empresas de Pequeno Porte optantes pelo Simples Nacional (Pert-SN)             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT
3315  2025-10-31  outubro  documento        None       None  DAS-MEI (Documento de Arrecadação Simplificada do Microempreendedor Individual)             Programa Especial de Regularização Tributária das Microempresas e Empresas de Pequeno Porte optantes pelo Simples Nacional (Pert-SN) Microempreendedor Individual             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT

[836 rows x 12 columns]

In [83]:
df.loc[
    df['data_inicio'].isnull() | 
    df['data_fim'].isnull() | 
    df['periodo_fato_gerador'].isnull(), 
    'periodo_fato_gerador'
].to_list()

['Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 '---------------',
 '---------------',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos',
 'Diversos']

In [84]:
df[['data_inicio', 'data_fim']].isnull().sum()

data_inicio    836
data_fim       836
dtype: int64

In [85]:
df[df['periodo_fato_gerador'].isnull()]

     data_evento   nome_mes tipo codigo_darf codigo_gps documento                                                                                                                              descricao periodo_fato_gerador                                                                            mes_url                                                                                           dia_url data_inicio data_fim
645   2025-02-28  fevereiro  gps        None       4324      None              Parcelamento Especial - Simples Nacional Art. 7º § 4º IN/ RFB nº 767/2007 - Pessoa jurídica optante pelo Simples Nacional                 None  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro/dia-28-02-2025         NaT      NaT
646   2025-02-28  fevereiro  gps        None       4359      None  Parcelamento para Ingresso no Simples Nacional - 2009 Art. 7º § 4º IN/RFB nº 902/2008 - Pessoa jurídica optante pelo Simples Nacional                 None  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro/dia-28-02-2025         NaT      NaT
647   2025-02-28  fevereiro  gps        None       4105      None                                                                                                                     Parcelamento – CEI                 None  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro/dia-28-02-2025         NaT      NaT
648   2025-02-28  fevereiro  gps        None       4135      None                                                 Programa de Regularização Tributária - PRT - Débitos Previdenciários - Pessoa Jurídica                 None  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro/dia-28-02-2025         NaT      NaT
649   2025-02-28  fevereiro  gps        None       4136      None                                                   Programa de Regularização Tributária - PRT - Débitos Previdenciários - Pessoa Física                 None  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro/dia-28-02-2025         NaT      NaT
...          ...        ...  ...         ...        ...       ...                                                                                                                                    ...                  ...                                                                                ...                                                                                               ...         ...      ...
3305  2025-10-31    outubro  gps        None       4995      None              Depósito Recursal Extrajudicial - Número do Título de Cobrança - Pagamento exclusivo na Caixa Econômica Federal (CDC=104)                 None    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT
3306  2025-10-31    outubro  gps        None       6009      None                                             Pagamento de Dívida Ativa Débito - Referência (Preenchimento exclusivo pelo órgão emissor)                 None    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT
3307  2025-10-31    outubro  gps        None       6203      None                                      Pagamento de Dívida Ativa Ação Judicial - Referência (Preenchimento exclusivo pelo órgão emissor)                 None    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT
3308  2025-10-31    outubro  gps        None       6300      None                                  Pagamento de Dívida Ativa Cobrança Amigável - Referência (Preenchimento exclusivo pelo órgão emissor)                 None    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT
3309  2025-10-31    outubro  gps        None       6408      None                                       Pagamento de Dívida Ativa Parcelamento - Referência (Preenchimento exclusivo pelo órgão emissor)                 None    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaT      NaT

[196 rows x 12 columns]

In [86]:
df.loc[
    df['data_inicio'].isnull() | 
    df['data_fim'].isnull() | 
    df['periodo_fato_gerador'].isnull(), 
    'periodo_fato_gerador'
]

148     Diversos
149     Diversos
150     Diversos
151     Diversos
152     Diversos
          ...
3311    Diversos
3312    Diversos
3313    Diversos
3314    Diversos
3315    Diversos
Name: periodo_fato_gerador, Length: 836, dtype: object

In [87]:
df[df['periodo_fato_gerador'] == '---------------']

    data_evento nome_mes           tipo codigo_darf codigo_gps documento                                                                                                                                                   descricao periodo_fato_gerador                                                                          mes_url                                                                                         dia_url data_inicio data_fim
335  2025-01-31  janeiro  declaracao_pj        None       None      None  Opção pelo Regime Especial Unificado de Arrecadação de Tributos e Contribuições devidos pelas Microempresas e Empresas de Pequeno Porte - Simples Nacional      ---------------  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-31-01-2025         NaT      NaT
336  2025-01-31  janeiro  declaracao_pj        None       None      None   Opção pelo Sistema de Recolhimento em Valores Fixos Mensais dos Tributos abrangidos pelo Simples Nacional (SIMEI) pelo Microempreendedor Individual - MEI      ---------------  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-31-01-2025         NaT      NaT

In [88]:
df.tail(100)

     data_evento nome_mes           tipo codigo_darf codigo_gps documento                                                                                     descricao   periodo_fato_gerador                                                                          mes_url                                                                                         dia_url data_inicio   data_fim
3221  2025-10-31  outubro           darf        2362       None      None  IRPJ - PJ obrigadas à apuração com base no lucro real - Demais Entidades - Estimativa Mensal          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3222  2025-10-31  outubro           darf        3373       None      None          IRPJ - Optantes pela apuração com base no lucro real - Balanço Trimestral (1ª quota)  Julho a Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-07-01 2025-09-30
3223  2025-10-31  outubro           darf        5993       None      None                      IRPJ - Optantes pela apuração com base no lucro real - Estimativa Mensal          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3224  2025-10-31  outubro           darf        2089       None      None                                                             IRPJ - Lucro Presumido (1ª quota)  Julho a Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-07-01 2025-09-30
3225  2025-10-31  outubro           darf        5625       None      None                                                             IRPJ - Lucro Arbitrado (1ª quota)  Julho a Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-07-01 2025-09-30
...          ...      ...            ...         ...        ...       ...                                                                                           ...                    ...                                                                              ...                                                                                             ...         ...        ...
3316  2025-10-31  outubro  declaracao_pj        None       None      None                               DCTFWeb - Declaração de Débitos e Créditos Tributários Federais          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3317  2025-10-31  outubro  declaracao_pj        None       None      None                                 DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3318  2025-10-31  outubro  declaracao_pj        None       None      None                                                 DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3319  2025-10-31  outubro  declaracao_pf        None       None      None                                 DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30
3320  2025-10-31  outubro  declaracao_pf        None       None      None                                                 DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01 2025-09-30

[100 rows x 12 columns]

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3321 entries, 0 to 3320
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   data_evento           3321 non-null   object
 1   nome_mes              3321 non-null   object
 2   tipo                  3321 non-null   object
 3   codigo_darf           2707 non-null   object
 4   codigo_gps            410 non-null    object
 5   documento             80 non-null     object
 6   descricao             3321 non-null   object
 7   periodo_fato_gerador  3125 non-null   object
 8   mes_url               3321 non-null   object
 9   dia_url               3321 non-null   object
 10  data_inicio           2485 non-null   datetime64[ns]
 11  data_fim              2485 non-null   datetime64[ns]
dtypes: datetime64[ns](2), object(10)
memory usage: 311.5+ KB

In [90]:
df.to_excel(f'../data/processed/agenda_tributaria_tratada_{ano_selecionado}.xlsx', index=False)

In [91]:
# Converter colunas de data para string no formato ISO
colunas_datas = ['data_evento', 'data_inicio', 'data_fim']
for col in colunas_datas:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce').dt.strftime('%Y-%m-%d')

# Gerar JSON como string (sem salvar ainda)
json_str = df.to_json(orient='records', force_ascii=False, indent=2)

# Remover as barras invertidas das URLs
json_str = json_str.replace('\\/', '/')

# Salvar no arquivo
with open(f'../data/processed/agenda_tributaria_outubro_{ano_selecionado}.json', 'w', encoding='utf-8') as f:
    f.write(json_str)

print(f"Arquivo '../data/processed/agenda_tributaria_outubro_{ano_selecionado}.json' gerado com sucesso!")

Arquivo '../data/processed/agenda_tributaria_outubro_2025.json' gerado com sucesso!

In [92]:
df['tipo'].value_counts().to_dict()

{'darf': 2707,
 'gps': 410,
 'declaracao_pj': 101,
 'documento': 80,
 'declaracao_pf': 22,
 'declaracao_imovel_rural': 1}

In [93]:
x = df[df['periodo_fato_gerador'] == 'Diversos']
x['tipo'].value_counts().to_dict()

{'darf': 520, 'documento': 60, 'gps': 58}

In [94]:
x[x['tipo'] == 'darf'].sort_values('codigo_darf', ascending=True).head(30)

     data_evento   nome_mes  tipo codigo_darf codigo_gps documento                                                                                                                                                                       descricao periodo_fato_gerador                                                                            mes_url                                                                                           dia_url data_inicio data_fim
2272  2025-07-31      julho  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/julho      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/julho/dia-31-07-2025         NaN      NaN
1941  2025-06-30      junho  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/junho      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/junho/dia-30-06-2025         NaN      NaN
2918  2025-09-30   setembro  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos   https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/setembro   https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/setembro/dia-30-09-2025         NaN      NaN
2595  2025-08-29     agosto  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos     https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/agosto     https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/agosto/dia-29-08-2025         NaN      NaN
1614  2025-05-30       maio  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos       https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/maio       https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/maio/dia-30-05-2025         NaN      NaN
945   2025-03-31      marco  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/marco      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/marco/dia-31-03-2025         NaN      NaN
608   2025-02-28  fevereiro  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro/dia-28-02-2025         NaN      NaN
1284  2025-04-30      abril  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/abril      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/abril/dia-30-04-2025         NaN      NaN
3251  2025-10-31    outubro  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaN      NaN
268   2025-01-31    janeiro  darf        1136       None      None                                           Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-31-01-2025         NaN      NaN
1942  2025-06-30      junho  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/junho      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/junho/dia-30-06-2025         NaN      NaN
2596  2025-08-29     agosto  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos     https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/agosto     https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/agosto/dia-29-08-2025         NaN      NaN
2919  2025-09-30   setembro  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos   https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/setembro   https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/setembro/dia-30-09-2025         NaN      NaN
1615  2025-05-30       maio  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos       https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/maio       https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/maio/dia-30-05-2025         NaN      NaN
946   2025-03-31      marco  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/marco      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/marco/dia-31-03-2025         NaN      NaN
269   2025-01-31    janeiro  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-31-01-2025         NaN      NaN
609   2025-02-28  fevereiro  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro/dia-28-02-2025         NaN      NaN
1285  2025-04-30      abril  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/abril      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/abril/dia-30-04-2025         NaN      NaN
2273  2025-07-31      julho  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/julho      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/julho/dia-31-07-2025         NaN      NaN
3252  2025-10-31    outubro  darf        1165       None      None  Parcelamento Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º             Diversos    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaN      NaN
1286  2025-04-30      abril  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/abril      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/abril/dia-30-04-2025         NaN      NaN
3253  2025-10-31    outubro  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaN      NaN
2920  2025-09-30   setembro  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos   https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/setembro   https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/setembro/dia-30-09-2025         NaN      NaN
1616  2025-05-30       maio  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos       https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/maio       https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/maio/dia-30-05-2025         NaN      NaN
1943  2025-06-30      junho  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/junho      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/junho/dia-30-06-2025         NaN      NaN
947   2025-03-31      marco  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/marco      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/marco/dia-31-03-2025         NaN      NaN
270   2025-01-31    janeiro  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro    https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-31-01-2025         NaN      NaN
2597  2025-08-29     agosto  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos     https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/agosto     https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/agosto/dia-29-08-2025         NaN      NaN
2274  2025-07-31      julho  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/julho      https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/julho/dia-31-07-2025         NaN      NaN
610   2025-02-28  fevereiro  darf        1194       None      None                                                    Parcelamento Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/fevereiro/dia-28-02-2025         NaN      NaN

In [95]:
testes = [
    "21 a 31/dezembro/2024",
    "Setembro/2025",
    "1º a 10/março/2025",
    "Outubro a Dezembro/2024",
    "Ano-calendário de 2024"
]

for t in testes:
    print(t, "=>", padronizar_periodo(t))

21 a 31/dezembro/2024 => (Timestamp('2024-12-21 00:00:00'), Timestamp('2024-12-31 00:00:00'))
Setembro/2025 => (Timestamp('2025-09-01 00:00:00'), Timestamp('2025-09-30 00:00:00'))
1º a 10/março/2025 => (Timestamp('2025-03-01 00:00:00'), Timestamp('2025-03-10 00:00:00'))
Outubro a Dezembro/2024 => (Timestamp('2024-10-01 00:00:00'), Timestamp('2024-12-31 00:00:00'))
Ano-calendário de 2024 => (Timestamp('2024-01-01 00:00:00'), Timestamp('2024-12-31 00:00:00'))

In [96]:
df

     data_evento nome_mes           tipo codigo_darf codigo_gps documento                                                        descricao   periodo_fato_gerador                                                                          mes_url                                                                                         dia_url data_inicio    data_fim
0     2025-01-06  janeiro           darf        8053       None      None                     IRRF - Títulos de Renda Fixa - Pessoa Física  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21  2024-12-31
1     2025-01-06  janeiro           darf        3426       None      None                   IRRF - Títulos de Renda Fixa - Pessoa Jurídica  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21  2024-12-31
2     2025-01-06  janeiro           darf        6800       None      None      IRRF - Fundo de Investimento sujeito à tributação periódica  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21  2024-12-31
3     2025-01-06  janeiro           darf        6813       None      None                            IRRF - Fundo de Investimento em Ações  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21  2024-12-31
4     2025-01-06  janeiro           darf        5273       None      None                                         IRRF - Operações de SWAP  21 a 31/dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-06-01-2025  2024-12-21  2024-12-31
...          ...      ...            ...         ...        ...       ...                                                              ...                    ...                                                                              ...                                                                                             ...         ...         ...
3316  2025-10-31  outubro  declaracao_pj        None       None      None  DCTFWeb - Declaração de Débitos e Créditos Tributários Federais          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01  2025-09-30
3317  2025-10-31  outubro  declaracao_pj        None       None      None    DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01  2025-09-30
3318  2025-10-31  outubro  declaracao_pj        None       None      None                    DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01  2025-09-30
3319  2025-10-31  outubro  declaracao_pf        None       None      None    DME - Declaração de Operações Liquidadas com Moeda em Espécie          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01  2025-09-30
3320  2025-10-31  outubro  declaracao_pf        None       None      None                    DOI - Declaração sobre Operações Imobiliárias          Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01  2025-09-30

[3321 rows x 12 columns]

In [97]:
palavras_chave = [
    "Simples Nacional", "DAS", "FGTS", "INSS", "DCTFWeb", "EFD-Reinf", "DEFIS", "DASN-SIMEI"
]
df_filtrado = df[df['descricao'].str.contains('|'.join(palavras_chave), case=False, na=False)]
df_filtrado

     data_evento nome_mes           tipo codigo_darf codigo_gps                                                                        documento                                                                                                                                                                                                                                                  descricao periodo_fato_gerador                                                                          mes_url                                                                                         dia_url data_inicio    data_fim
72    2025-01-15  janeiro           darf        8741       None                                                                             None  CIDE - Remessas ao Exterior - Contribuição de Intervenção no Domínio Econômico incidente sobre remessa de importâncias ao exterior nas hipóteses tratadas no art. 2º da Lei nº 10.168/2000,com a alteração introduzida pelo art. 6º da Lei nº 10.332/2001        Dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-15-01-2025  2024-12-01  2024-12-31
100   2025-01-15  janeiro  declaracao_pj        None       None                                                                             None                                                                                                                                                               EFD-Contribuições - Escrituração Fiscal Digital das Contribuições incidentes sobre a Receita        Novembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-15-01-2025  2024-11-01  2024-11-30
101   2025-01-15  janeiro  declaracao_pj        None       None                                                                             None                                                                                                                                             DCTFWeb - Declaração de Débitos e Créditos Tributários Federais Previdenciários e de Outras Entidades e Fundos        Dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-15-01-2025  2024-12-01  2024-12-31
102   2025-01-15  janeiro  declaracao_pj        None       None                                                                             None                                                                                                                                                                          EFD-Reinf - Escrituração Fiscal Digital de Retenções e Outras Informações Fiscais        Dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-15-01-2025  2024-12-01  2024-12-31
111   2025-01-20  janeiro           darf        4574       None                                                                             None                                                                                                                                                                                                              PIS/PASEP - Entidades financeiras equiparadas        Dezembro/2024  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/janeiro/dia-20-01-2025  2024-12-01  2024-12-31
...          ...      ...            ...         ...        ...                                                                              ...                                                                                                                                                                                                                                                        ...                  ...                                                                              ...                                                                                             ...         ...         ...
3314  2025-10-31  outubro      documento        None       None                               DAS (Documento de Arrecadação do Simples Nacional)                                                                                                                       Programa Especial de Regularização Tributária das Microempresas e Empresas de Pequeno Porte optantes pelo Simples Nacional (Pert-SN)             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaN         NaN
3315  2025-10-31  outubro      documento        None       None  DAS-MEI (Documento de Arrecadação Simplificada do Microempreendedor Individual)                                                                                          Programa Especial de Regularização Tributária das Microempresas e Empresas de Pequeno Porte optantes pelo Simples Nacional (Pert-SN) Microempreendedor Individual             Diversos  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025         NaN         NaN
3316  2025-10-31  outubro  declaracao_pj        None       None                                                                             None                                                                                                                                                                                            DCTFWeb - Declaração de Débitos e Créditos Tributários Federais        Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01  2025-09-30
3317  2025-10-31  outubro  declaracao_pj        None       None                                                                             None                                                                                                                                                                                              DME - Declaração de Operações Liquidadas com Moeda em Espécie        Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01  2025-09-30
3319  2025-10-31  outubro  declaracao_pf        None       None                                                                             None                                                                                                                                                                                              DME - Declaração de Operações Liquidadas com Moeda em Espécie        Setembro/2025  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro  https://www.gov.br/receitafederal/pt-br/assuntos/agenda-tributaria/2025/outubro/dia-31-10-2025  2025-09-01  2025-09-30

[465 rows x 12 columns]

### Quando que o cara consulta e para que ele precisa consultar esses dados?
### Faz sentido o cliente ver apenas um mes ? pensando que talvez seja interessante ele ter uma previsibilidade das contas que ele à pagar.
### Quais sao os tributos que o cara paga?

### Sugestao de Tabela

```SQL
CREATE TABLE AGENDA_TRIBUTARIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    DATA_EVENTO DATE,
    NOME_MES VARCHAR2(255),
    TIPO VARCHAR2(255),
    CODIGO_DARF VARCHAR2(255),
    CODIGO_GPS VARCHAR2(255),
    DOCUMENTO VARCHAR2(4000),
    DESCRICAO VARCHAR2(4000),
    PERIODO_FATO_GERADOR VARCHAR2(4000),
    MES_URL VARCHAR2(4000),
    DIA_URL VARCHAR2(4000),
    DATA_INSERCAO TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (ID)
);
```

In [98]:
# --- PARTE 2: A CONEXÃO E INSERÇÃO NO BANCO DE DADOS ---

# Configurações de conexão com o banco de dados Oracle
# IMPORTANTE: Substitua os placeholders abaixo com suas credenciais reais
user = 'breno'
password = 'breno123'
host = 'host'
port = '1521'
service_name = 'service_name'

# Cria a string de conexão usando o driver oracledb
conn_str = f'oracle+oracledb://{user}:{password}@{host}:{port}/?service_name={service_name}'

try:
    # Cria o "engine" de conexão com o banco de dados
    engine = create_engine(conn_str)
    
    # Usa o método to_sql() do pandas para inserir o DataFrame
    df.to_sql(
        name='AGENDA_TRIBUTARIA',  # Nome da tabela no banco de dados
        con=engine,               # A conexão com o banco de dados
        if_exists='append',       # Opção para adicionar novos registros
        index=False               # Não insere o índice do DataFrame como uma coluna
    )
    
    print("Dados inseridos com sucesso na tabela AGENDA_TRIBUTARIA!")

except Exception as e:
    print(f"Ocorreu um erro ao inserir os dados: {e}")
finally:
    # Garante que a conexão será fechada corretamente
    if 'engine' in locals():
        engine.dispose()

Ocorreu um erro ao inserir os dados: name 'create_engine' is not defined